In [1]:
import json
import polars as pl

In [2]:
DIR = "/mnt/common-ssd/group-dirs/tkom-2026-project/pickwell"
CITY = "budapest"

In [3]:
with open(f"{DIR}/{CITY}_old/id_lookup/id_lookup.json", "r") as fp:
    old_lookup = json.load(fp)

In [4]:
with open(f"{DIR}/{CITY}/id_lookup/id_lookup.json", "r") as fp:
    new_lookup = json.load(fp)

In [5]:
old = pl.DataFrame({"raw_id": old_lookup.keys(), "old_id": old_lookup.values()}).sort(
    "old_id"
)
new = pl.DataFrame({"raw_id": new_lookup.keys(), "new_id": new_lookup.values()})
new = (
    new.with_columns(
        pl.col.raw_id.str.split_exact(".", n=1).struct.rename_fields(
            ["raw_id", "aid_type"]
        )
    )
    .unnest("raw_id")
    .sort("new_id")
)

In [6]:
old.join(new, on="raw_id").filter(pl.col.aid_type.is_null())

shape: (0, 4)
┌────────┬────────┬──────────┬────────┐
│ raw_id ┆ old_id ┆ aid_type ┆ new_id │
│ ---    ┆ ---    ┆ ---      ┆ ---    │
│ str    ┆ i64    ┆ str      ┆ i64    │
╞════════╪════════╪══════════╪════════╡
└────────┴────────┴──────────┴────────┘

In [7]:
old.join(new, on="raw_id")

shape: (1_652_702, 4)
┌─────────────────────────────────┬─────────┬──────────┬─────────┐
│ raw_id                          ┆ old_id  ┆ aid_type ┆ new_id  │
│ ---                             ┆ ---     ┆ ---      ┆ ---     │
│ str                             ┆ i64     ┆ str      ┆ i64     │
╞═════════════════════════════════╪═════════╪══════════╪═════════╡
│ 0000051fc26276495c5a9ab1753a70… ┆ 1       ┆ AAID     ┆ 1       │
│ 000006ba36dda4e4fe39d406a1299b… ┆ 2       ┆ AAID     ┆ 2       │
│ 0000142bfd04443d8461e7613e4f60… ┆ 3       ┆ AAID     ┆ 3       │
│ 0000278addb0b7cf048517051ed3f6… ┆ 4       ┆ AAID     ┆ 4       │
│ 00003395f709c02f5ddad2eff4d4bf… ┆ 5       ┆ IDFA     ┆ 5       │
│ …                               ┆ …       ┆ …        ┆ …       │
│ ffffdd54c47c4049a25f28d8acd6f8… ┆ 1652456 ┆ AAID     ┆ 1652698 │
│ ffffde9a4de3d5a6da2af133e3de47… ┆ 1652457 ┆ AAID     ┆ 1652699 │
│ ffffe113b3e0226a7579cd7e8270dd… ┆ 1652458 ┆ IDFA     ┆ 1652700 │
│ ffffeb51c8daf2250d194a298fbb3c… ┆ 1652459 ┆ AAID     ┆ 1652701 │
│ ffffec76c36b62f621ac683d6821bb… ┆ 1652460 ┆ IDFA     ┆ 1652702 │
└─────────────────────────────────┴─────────┴──────────┴─────────┘