In [1]:
import json
from pathlib import Path

import pandas as pd
import polars as pl
import yaml
import numpy as np
import structlog
from create_id_lookup import collect_ids, create_lookup, create_partitions
from common import daterange

with open("../config.budapest.yaml", "r") as fp:
    config = yaml.safe_load(fp)

days = []
for i in config["days"]:
    days += list(daterange(i["start"], i["end"]))

log = structlog.get_logger()

In [2]:
OUTPUT = f"{config['dirs']['output']}/{config['city']}/id_lookup"

In [3]:
pl.DataFrame([["a", "b", "c"]], schema=["id_with_type"]).with_row_index(
    "device_id", offset=1
)

shape: (3, 2)
┌───────────┬──────────────┐
│ device_id ┆ id_with_type │
│ ---       ┆ ---          │
│ u32       ┆ str          │
╞═══════════╪══════════════╡
│ 1         ┆ a            │
│ 2         ┆ b            │
│ 3         ┆ c            │
└───────────┴──────────────┘

In [3]:
try:
    with open(f"{OUTPUT}/id_lookup.json", "r") as fp:
        lookup = json.load(fp)
except FileNotFoundError:
    # runs 30 minutes for Budapest data
    ids = collect_ids(
        days,
        config["dirs"]["raw_source"],
        id_column=config["id_column"],
        id_type_column=config["id_type_column"],
    )
    log.info(f"number unique devices: {len(np.unique(ids))}")

    lookup = create_lookup(ids)

    Path(OUTPUT).mkdir(parents=True, exist_ok=True)
    with open(f"{OUTPUT}/id_lookup.json", "w") as fp:
        json.dump(lookup, fp, indent=1)

In [10]:
lookup

{'0000051fc26276495c5a9ab1753a70dd.AAID': 1,
 '000006ba36dda4e4fe39d406a1299b67.AAID': 2,
 '0000142bfd04443d8461e7613e4f600d.AAID': 3,
 '0000278addb0b7cf048517051ed3f688.AAID': 4,
 '00003395f709c02f5ddad2eff4d4bfa2.IDFA': 5,
 '0000370e6272b18907fde190edd5c728.AAID': 6,
 '00004246bf0c7f1595a05eb7e5f3fdc5.AAID': 7,
 '000052a8dbca773ddf5257da94247d6b.AAID': 8,
 '000054d2c890c308b0649cfd70f32b68.IDFA': 9,
 '00005fa780b24932682f16b31a5c69f6.IDFA': 10,
 '00005feda0bedb6cca9afcecb887007b.AAID': 11,
 '00006c0dc1e9ab0527385f31f2267385.AAID': 12,
 '000073fd63cab3cf43c34b3f466e2534.AAID': 13,
 '0000752e8d10818f9b59ad187a2a0893.AAID': 14,
 '000086c9027b7ec6809ac71565289741.AAID': 15,
 '00008d27fffdcef8e3102249c33c93e9.AAID': 16,
 '00008f26fbce9c249017e36c850d4e4c.AAID': 17,
 '0000a0688997392e43d0846aeb8784dc.AAID': 18,
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID': 19,
 '0000a54321512252c9b3362e3e5e0ae3.AAID': 20,
 '0000a6824521da23c81d823eb6b61416.AAID': 21,
 '0000b590d54908ea5a037096b9214ce2.AAID': 22,
 '0000d33977a4566504e638592ea15f37.AAID': 23,
 '0000d391434c922fa7c6db139907819d.IDFA': 24,
 '0000d7ead16b81d24db89a02c51a3db7.AAID': 25,
 '0000da197f9a6f6d45f62bd55dcdfa79.AAID': 26,
 '0000e24c4b6adb1c2fc9481149db75e6.AAID': 27,
 '00011ad382968502b6cef688000178b2.AAID': 28,
 '00012c23c1ef81bf6f3912bbe64bb861.AAID': 29,
 '0001387e13b731411ff461b94aca9264.AAID': 30,
 '00013dd30f845e8618286c642679636f.AAID': 31,
 '00014538119345c90f616421c422e193.IDFA': 32,
 '0001477976aad52f1e6e29ffc837a283.AAID': 33,
 '00014aae8b4854aae41d0f4b8f8322da.AAID': 34,
 '00014b712020806547dd406c6ff7c3a6.AAID': 35,
 '00014bd600e2dec25af8a073e27c15db.AAID': 36,
 '0001595ad1bb498576f1d20e1c0ffd42.AAID': 37,
 '000159f8f4dfb5d8c4952d23e08f884b.AAID': 38,
 '00016b388656b3765fa34646840ec51a.AAID': 39,
 '0001852c12c7af746be15a824beddfc0.AAID': 40,
 '000195ab6c3758b5c1f8bdf563229bfa.AAID': 41,
 '00019a3f2e8e70b015a3266bfc14c026.AAID': 42,
 '00019f447b3846e7a1c69c1ccc2a64d8.AAID': 43,
 '0001a66aed1e895899eaec1aa0c36688.AAID': 44,
 '0001aa6ebe5665127c1df51c036ac917.AAID': 45,
 '0001accbd364413c42ba4ed7a4d3f10f.AAID': 46,
 '0001b59e5733dddbe8fc96a0f0523288.AAID': 47,
 '0001b831c40ac0e5b76a7ab54fa2f061.AAID': 48,
 '0001bc23ada5e3f79a22612d94c023e2.IDFA': 49,
 '0001c69cb95832401662a40c09c26e70.AAID': 50,
 '0001ca3f36a2c6b3f3f2396ef9906ddf.AAID': 51,
 '0001cb07909c0be73dadfc57ad54b328.AAID': 52,
 '0001dd476e64d0247904febdee7c2c6c.IDFA': 53,
 '0001dfa33f7e89161d492b12e1db35a4.AAID': 54,
 '0001eb0af0eefb73daddf6e79fdc260b.AAID': 55,
 '0001ebcd4e9c2bd958f0d9aba927fd2c.AAID': 56,
 '0001f855f42b341007075d3b17636192.AAID': 57,
 '0001fe13e2ca3e5fa365d8630e3a11ad.AAID': 58,
 '0002059345975e01f538f944b1f3285d.AAID': 59,
 '00020c77023a159d540c8fe0983561dc.AAID': 60,
 '00021b1c5bd05aac3c529f6ab1d26ab8.AAID': 61,
 '00021e8eae14000f2c26b4c5d77b79a4.AAID': 62,
 '0002226a900567747f8c4ba2c47f8b66.AAID': 63,
 '000225d68b8b99d2683a8ba25f21446f.AAID': 64,
 '00022b49534245ca27d1179873b37900.AAID': 65,
 '000240971c2eb61c9bc44f7b4a61c16c.AAID': 66,
 '0002491483b2cf364c196cd047f15562.AAID': 67,
 '0002527b6b732d47a495b31c357c1e61.AAID': 68,
 '000267ab6baedc40a0de922b0d80b66b.AAID': 69,
 '00029022909d97d05ae887b19be3d218.AAID': 70,
 '0002a2827cefbd027b4338d77cb50f72.AAID': 71,
 '0002ab5a429a536d8f4fa1678b4b8adb.AAID': 72,
 '0002e4a560ed6419a65f881187971328.AAID': 73,
 '0002fbf173b5ed294bb0db125ba2f322.AAID': 74,
 '0002fc7753d31beb89039ee13d4893c5.AAID': 75,
 '00030aff5a9132ef68bdf0f2b12c7eb6.AAID': 76,
 '00031a9355cc79f4f865af3470ba6963.AAID': 77,
 '00031c195d10646660acf8f86c9e5eac.AAID': 78,
 '000328e33d5d5ce0e6a68a728a8f69da.IDFA': 79,
 '0003330e5bb58c2cf4a927b075ef2cf9.AAID': 80,
 '000333270fe855d6f6076a62d18f6c5e.AAID': 81,
 '000333db095835105d676668b76efdad.AAID': 82,
 '000335b2feb70e726f08e7ff9c1337f8.AAID': 83,
 '00033d7709e86e74f4491b7883d7e43f.AAID': 84,
 '00033ed397491a6fd6f00d1c26abd759.AAID': 85,
 '000340ed10297297802d301cba1c45b0.AAID': 86,
 '00034bb0298a87faf33a5b163bba42ad.AAID': 87,
 '000363b6faed4d5f26742a6edf7d10c7.AAID': 88,
 '0003693d7d106c83e5c451c1a667df25.IDFA': 89,
 '000371dd5debe9eab7dfd6e3653614b1.AAID': 90,
 '0003734b6421c51ffeec505279d5f5fe.AAID': 91,
 '00037978f950f30ae22a003808ee8868.AAID': 92,
 '00037ca8912b6d0eb0475b7f8b932b9b.AAID': 93,
 '000388c397949da8d3d39263ce9f79ff.AAID': 94,
 '00038f4e2aab629264fbfe440a3b3a7f.AAID': 95,
 '0003a402ddf1ff3f869ae1637330f15c.AAID': 96,
 '0003ac530ffa3ba42a5ac5aed15b3716.IDFA': 97,
 '0003b8731c9540d7b8a8e05b0cd44589.IDFA': 98,
 '0003c0811080d7d02bdbe4b150438039.AAID': 99,
 '0003cd9fc573cf417a99fa5b8b02a6f1.AAID': 100,
 '0003cf57e33ae1806f83995ca7568735.AAID': 101,
 '0003d5f6f751be9479365aa8a12da189.IDFA': 102,
 '0003d9f771a48d0fc1497db272d5c6fb.AAID': 103,
 '0003dcffbffc00273df5fd65f4949362.AAID': 104,
 '0003ec8768239a69acd96204d6b00a73.AAID': 105,
 '0003f5393e0247fb7dccd82e87f0da76.AAID': 106,
 '0003fb36df8f92e51d6776ae58cb2a79.AAID': 107,
 '000416c7e2998a81ee7929fbc3d59484.AAID': 108,
 '0004177980c9f7a7b1c0284261052843.AAID': 109,
 '000423c350c19177a9c872708de19a6d.AAID': 110,
 '00042bc69cb32733af1a90fd73df5e14.AAID': 111,
 '00043dfd23f533038f4a74ea26284cdd.AAID': 112,
 '0004412519d09183a467d9a6a34e4884.AAID': 113,
 '0004438c2fcb0f0e0097faace5488602.AAID': 114,
 '0004462f633dcde0fa2fd31138ae15bf.IDFA': 115,
 '000450dfc9b043c7670b1428f59e1ed4.AAID': 116,
 '00046418ced7960d1c82c1f63e8feb32.IDFA': 117,
 '000469f3811e7e9bba83b5526422c656.AAID': 118,
 '00046e040606e69002eea04e83b6ad07.IDFA': 119,
 '00046f74293605b846eaf11570f28826.AAID': 120,
 '00047294d1e4bd503b358b1de735c2e5.AAID': 121,
 '000472a6353190bdde909e20c179ec1d.AAID': 122,
 '0004756d594715dcfbf55faa93bcd200.IDFA': 123,
 '000477a584479b280678e53de5151584.AAID': 124,
 '00047941620a15971ed2852e0359f1a4.AAID': 125,
 '00047cf9bfdab12e3b9e27c41f73f0ed.AAID': 126,
 '00047e0ca8d6e69c75579e504f301f10.AAID': 127,
 '000492be80904b3f243d3d75ebc17817.AAID': 128,
 '0004936f5d5f9e889ab0a9b03e1b9c59.AAID': 129,
 '00049979866831366e6a0868b565bdff.IDFA': 130,
 '00049a147aa947d5b8b6d7d2d1f9dfa7.AAID': 131,
 '00049a8ec4c4c7bffcd440324aba32cc.AAID': 132,
 '00049ae58cac95ff4e2579d393603f37.AAID': 133,
 '0004b570293de15a97b8f179c1f27270.AAID': 134,
 '0004b5a343de928c2eebd374cc99a394.AAID': 135,
 '0004b60b704faca2ff2db28046095f2f.AAID': 136,
 '0004d09967f60805298d633d3d2c5081.AAID': 137,
 '0004d0e7b671035f7f08296a7ac1cc9c.AAID': 138,
 '0004d3373c9ce0b3d496b6d5c17f3303.AAID': 139,
 '0004e371a0ab3008c974294f81b4cca3.AAID': 140,
 '0004f4931073805cee01b074f3d83c74.IDFA': 141,
 '0004fafc31603acf6bbc782dd9cc772a.AAID': 142,
 '0004ff89736a0f050670de33216cd790.IDFA': 143,
 '0005028ededb45040c190338992ad100.IDFA': 144,
 '0005030fa4ff547ae8e9bc8b79119c99.AAID': 145,
 '0005116f1f448b548f649c52870782b7.AAID': 146,
 '0005155ace1ce64f967807edf43b393a.IDFA': 147,
 '00051dfe2f5bb9af768860e2ab3240fb.AAID': 148,
 '0005325ebe417af72524eaf6de1d4fab.AAID': 149,
 '0005364cf5afb66539bad17dc89fef21.IDFA': 150,
 '00053e761ac7a04392019113dbd81b25.AAID': 151,
 '00055a7559fe47e760d93fa66226e9de.AAID': 152,
 '000567b4b6fa4654c25697317ec7757a.AAID': 153,
 '0005722774bbcfea9d9f1dbe073c8021.AAID': 154,
 '00057cff06ef94096fc6d1623503256a.AAID': 155,
 '0005830e04f56ea36c12449f4f36b0d5.AAID': 156,
 '000584e0ec5f376df9ff49f83891e3d2.AAID': 157,
 '00058bbdc71899fa526ddefb8cc87d6c.AAID': 158,
 '0005afb9fa7b381ae9ed11c2373e0f3a.IDFA': 159,
 '0005b53a959a812d62a4e50394657dd3.AAID': 160,
 '0005b73803271bd035039b4d98474a97.AAID': 161,
 '0005c1708e2e517a2db3243a6f3fb62b.AAID': 162,
 '0005c30e55d56f8286ee0af989cfd52e.AAID': 163,
 '0005c585a981a0fb6dae9ca020cc35b2.IDFA': 164,
 '0005e50b995b57c62c7261592f682146.AAID': 165,
 '0005e9486e291e8b72f4d39c49fbdc4d.AAID': 166,
 '0005f94d1eee31cd7f10be891dee2a4d.AAID': 167,
 '000630bac24c530ab08651c7e7eaaff0.AAID': 168,
 '000633e35a10596a516f6c168187aeaa.AAID': 169,
 '0006444fc8ad3509358b4efbd25d37f3.AAID': 170,
 '000649ad7313019a30f8c8c78dd7b310.AAID': 171,
 '00064bc7e05b9262b66b503a8ff24e22.AAID': 172,
 '00064dc0c83f3b615cca12fcfcc82384.AAID': 173,
 '000655881d5e2cc2a6d5c3a95387a29c.AAID': 174,
 '00065b290aeabb1eb44d298146f957e7.AAID': 175,
 '00066d3aed63e3c4a8bf390a897e4c9d.AAID': 176,
 '00066d5b21a457876301cd350d0fc4e4.AAID': 177,
 '000676b45bd23a313da32db0466505dd.AAID': 178,
 '000699aeafc5c1bc4eb5afe95fba8264.IDFA': 179,
 '00069b7af75a91c76967fac94da05bb9.AAID': 180,
 '00069cbd4fcca42393e0c5db40c61193.AAID': 181,
 '0006b03bc103913a2cd5371bf7fb26e0.AAID': 182,
 '0006bc61e891ee7298c6dc476e894036.IDFA': 183,
 '0006c07173b668f338cbab3218957e29.AAID': 184,
 '0006c1fe36bc1fc99ca8f680e88032bd.AAID': 185,
 '0006c43bfb38c4514197cb712176cd90.IDFA': 186,
 '0006d1f45c5170c1040f87f27a18ec8d.AAID': 187,
 '0006d69347e66e612510dd3dd5de6752.IDFA': 188,
 '0006d73d3591c5150b866b7fa8a18fb4.AAID': 189,
 '0006db10e6997ef76061ad0870146c5e.AAID': 190,
 '0006de8d294677403ff7ca01b13a0fff.AAID': 191,
 '0006e0dc2de05ed2e8845fef406ee0b1.AAID': 192,
 '0006e63812923c4af1be4e367073eb37.AAID': 193,
 '00070512f5733fd9cf5797c419735354.AAID': 194,
 '00070c2582dceb3f51779a0620162f3e.AAID': 195,
 '00070e111288de0686c5845c748e3954.AAID': 196,
 '00070f602a2b0ab70fd08dbb000fcbd6.AAID': 197,
 '0007155a77c25193e4949858c821dc27.IDFA': 198,
 '0007346a74a685fb8efd9be5f1dea9ef.IDFA': 199,
 '00073586a7af8171b24d24db5f9f5d93.AAID': 200,
 '000740476d093d1930253b4dc61c1541.AAID': 201,
 '00074389de6a2fa08a3d8fa5ffb724d4.AAID': 202,
 '0007486a38007d7cf27d4cf02125038d.AAID': 203,
 '000748e1536730667375bfafb6897a80.IDFA': 204,
 '000757a786ac96cd31c55c3f2db9a2d2.AAID': 205,
 '00075b6c96d8f1b41b18677e84d92906.AAID': 206,
 '000765aaaf862b57078ccab94d122a3d.AAID': 207,
 '000775f8d521b1af96e4f05a87916407.AAID': 208,
 '00077afe6531de4b54511fb36d84d2e1.AAID': 209,
 '0007834925bffc24afa3a7bfec8fbe64.AAID': 210,
 '00078904fdd18f56d93abf8d4c3b89e6.AAID': 211,
 '00078b6c1e63227048fbd3b43023b837.AAID': 212,
 '0007958669b5f62a9d56d58749ed3781.AAID': 213,
 '000796618f320551b20b83ffb69c6d36.AAID': 214,
 '0007a02d921000a975a2d3edaf2079d4.AAID': 215,
 '0007a92af7e5f5e1398b7a6b5685d1d4.AAID': 216,
 '0007b13e8f5eb920c6f40b24bd7856ab.AAID': 217,
 '0007c95298c161802452a51fd2a7778f.IDFA': 218,
 '0007d3f8f28daf80f40708bdbfddf2f8.AAID': 219,
 '0007ddedc44f04b41e30bea7a8a5ec3c.AAID': 220,
 '0007e0ef406d912555cc18dab7d61231.AAID': 221,
 '0007eeac107786d32337c13aedb55a75.AAID': 222,
 '0007f25e0dd53af64355989b07038387.AAID': 223,
 '0007f9a5f7a4756c90934348530a6113.AAID': 224,
 '00080989d696f9b43029586ba1974990.AAID': 225,
 '000813cb4a86360d5f3cb3e3f5db2175.AAID': 226,
 '000821371cc5f3e6f410b528acc0e869.AAID': 227,
 '0008276c979e01e73ef7f48f9d9b545d.AAID': 228,
 '00082afa048be4caafeae0cb6f5717ed.AAID': 229,
 '0008305159cb518d767155fc0d1f10c7.AAID': 230,
 '0008451f79690e6df2ea279697df5c41.AAID': 231,
 '000852c1921d9fb6f0db32864faef31f.AAID': 232,
 '00085a61e94d9d72407c083a43a7d0f1.AAID': 233,
 '00086104000447f6d5aeb58c6eb760ae.AAID': 234,
 '0008709f3866f41d536fe488c2431897.AAID': 235,
 '000872c1d06a2c8b23d24ad54ceaf521.AAID': 236,
 '00087a2c304d760bf2e01f1ed4d3e668.AAID': 237,
 '00087e00053f831de58ca599c176cba5.AAID': 238,
 '00089274109d2ea07343dd042454c5e4.AAID': 239,
 '0008974972fab84d1539eae77b58bf0e.AAID': 240,
 '00089a8b73cb957ce260439d9f77cac4.AAID': 241,
 '0008cd244779a02a6d6cef489afdc058.AAID': 242,
 '0008da491462627faeca5ef89592097d.AAID': 243,
 '0008e284c0c24f1fbb4f79f11cfc5523.AAID': 244,
 '0008e2f57eafa9a11ab6977f74fba752.AAID': 245,
 '0008e5831b90c3cb6c59bc96edc114f0.IDFA': 246,
 '0008e62928469ac77141184452092c6d.AAID': 247,
 '0008ecf3d2da40111e11d69f08a2d0d9.AAID': 248,
 '0008f47d08b7eaef47cf7a8d917398fa.IDFA': 249,
 '0008fa6e517f217604bc04eca229fbab.AAID': 250,
 '0008feda96e99dfc4a3f5b946520f921.IDFA': 251,
 '000914a113cff537756b3ff6033c52c0.AAID': 252,
 '00091b78f04a700b3fb91c91177150aa.AAID': 253,
 '000934e8587b96e1ccd1c93c182700a9.AAID': 254,
 '0009449807f0bfa8ea0147e42eb5153e.AAID': 255,
 '00095ab8b67ea6935dce83f9f3da89f1.AAID': 256,
 '00095c63ab6eb2c1e93b39b2e8ba2c0a.AAID': 257,
 '00095d167b7df98e25d7e5f3dedcc097.AAID': 258,
 '0009614e2239d83c9936696d3c987501.AAID': 259,
 '000961f87444ed68d776c422b12f0b90.AAID': 260,
 '0009705c7c2eb73a8c7f6995e540fcf8.AAID': 261,
 '000971808e46e8873e19170a657b09a2.AAID': 262,
 '000974a8cfa7ea5503a97285b466f91a.AAID': 263,
 '00097f2c874bb19cf3bd927bf13fb2a2.IDFA': 264,
 '0009850c8c46d51ac6e71b57f7802603.AAID': 265,
 '00098e006dfe7e81f7886fcff55c0c11.AAID': 266,
 '000991b17f41bd0a58f214feec1d0bd2.IDFA': 267,
 '00099e9ad3eeea51e5e2ad4a6f0ebc40.AAID': 268,
 '0009a0ebfee57c560c1b1a60e2988fa2.AAID': 269,
 '0009a4e848462e60d3af73e11b0c4b54.IDFA': 270,
 '0009a648cab8108c8d30dde6a29002d2.AAID': 271,
 '0009b08db0ee66771dfe60a8fb7e6b31.AAID': 272,
 '0009b430a554b445cfeaa7bb1408ff16.AAID': 273,
 '0009bb462e52ef05811dca313b91314e.AAID': 274,
 '0009bb5d695ee589a2d78d2bc6d33594.AAID': 275,
 '0009c18b34171b2bbb3045092b72fd02.AAID': 276,
 '0009c8bae70e051eee00687c910a1a67.IDFA': 277,
 '0009ec43e5827ad3d74807e632ad9170.AAID': 278,
 '0009ef4a99ff2b24aec6cb4da37ad685.AAID': 279,
 '0009f4f2d5a9d7febfc34102a311f4f9.AAID': 280,
 '000a113fa53eec99fa2ad433c586eddd.IDFA': 281,
 '000a1579032bd2f320058f33375d8dfa.AAID': 282,
 '000a15ecf229ed48169b1cf48c204051.AAID': 283,
 '000a1864fe66fb534fa0d2d3d198fe35.AAID': 284,
 '000a47276444bbbb57c34d9964f87057.AAID': 285,
 '000a491a22f2a7878b671839fead92dd.AAID': 286,
 '000a49fe31115171608f782892c2d272.AAID': 287,
 '000a4a43e9beaece5840c80745bf2227.AAID': 288,
 '000a4ee0d3faeafbea99cc9f76d9fe68.AAID': 289,
 '000a4fcd806785ba6ee864bef73c1f36.AAID': 290,
 '000a506dc9f76c8381d9792bd50dd923.IDFA': 291,
 '000a5d7be9ad26502a6f987ec4dffee4.AAID': 292,
 '000a65d1145533f5e6854fff221a98b6.AAID': 293,
 '000a7c2652982b11dacf634aaeab711f.AAID': 294,
 '000a86c28555b3e3e880747002049b55.AAID': 295,
 '000a87f8905f0e8038cb89f0b7b3e148.AAID': 296,
 '000a9f752aa95a706ee8bb7f0670807b.AAID': 297,
 '000aa1d6aa3ff0124d805d68ab859948.AAID': 298,
 '000aa2af121a6b03606f0f76e005d029.AAID': 299,
 '000aaf696ae32f5a41a39c01e67c4842.IDFA': 300,
 '000ab2a898f3d7a6e5c6d827f66f41fc.AAID': 301,
 '000ac40f269be9451458cc1f9384feea.AAID': 302,
 '000ac92ebf8d3c0821fd432311318f05.AAID': 303,
 '000acd199683d2457607c7751426edbb.AAID': 304,
 '000aebe66cd845fdc22ee18d34751124.AAID': 305,
 '000aeda6e1f77df517b4d7168a0443fc.AAID': 306,
 '000af7a4d83733068400c4ad1bed4166.AAID': 307,
 '000aff0286a1d603a5009edb6155679e.AAID': 308,
 '000b033e03434b3406422bfbc2f40bcf.IDFA': 309,
 '000b07f1a60ca0127dc07d991ed5e05d.AAID': 310,
 '000b0f9e8a3d90618ec272b5538efffa.AAID': 311,
 '000b12cf1271ae888554c78ea0e6b7a7.AAID': 312,
 '000b20048128a4b118d541035826f7bf.AAID': 313,
 '000b272db5d9722a4dad936f2fca87af.AAID': 314,
 '000b2baffc2ab4071294b0e33569a517.AAID': 315,
 '000b32c2ab608be2db5f75e8caf8fef4.AAID': 316,
 '000b336e095ae31fabad9dbcde670e18.IDFA': 317,
 '000b5d36f1961379dfef28a44eb52658.IDFA': 318,
 '000b60a4ba84bd5ae563a32268d01356.AAID': 319,
 '000b678d13d3a609044f583463742138.IDFA': 320,
 '000b67dee3832cdf5bff809be393d71f.AAID': 321,
 '000b6a03235e0c336d71d390ac3cf85c.IDFA': 322,
 '000b6cf1328c45f91fe395d853cb93c7.AAID': 323,
 '000b7cc3be4293a59d484bd159bee91f.AAID': 324,
 '000b81dc510852939cfddb7e5f169262.AAID': 325,
 '000b8e7719645a78909a3214aa8e0270.AAID': 326,
 '000bb5dddc73797155854a1b37c5a394.AAID': 327,
 '000bb8f051814d48c278ce215acfcf79.AAID': 328,
 '000bea178ea1208fc155b6c8ab4d7f8e.AAID': 329,
 '000befc6217f344b30cb729f21cd0994.AAID': 330,
 '000bfb638bc9a8da524e0c295f7cc366.AAID': 331,
 '000c0156837060ae0bfac5348d158f7b.IDFA': 332,
 '000c08d53099598c10728bbf97516c46.AAID': 333,
 '000c0c479a4566054585e8443f200bc6.AAID': 334,
 '000c137ecbe792f916e457e95370025c.AAID': 335,
 '000c1e90a9402d85f921c1f9d783ce0d.AAID': 336,
 '000c24932bfb1b9d5fd8236b1a4bf89e.AAID': 337,
 '000c2f466f621e84106208be34e63e4c.AAID': 338,
 '000c3508d481e4726e1c56ccc7d77590.AAID': 339,
 '000c392f962cb5da8ded9816c4e624dc.AAID': 340,
 '000c3a24dbc53fbe3c0127e581a18bd7.AAID': 341,
 '000c3c75013be7bcd656f877fecba863.AAID': 342,
 '000c3f6fc6cdab9d8707eab0c84fdaf5.AAID': 343,
 '000c4e5eb9e29407b7e6798ba0aa0f57.AAID': 344,
 '000c4ef5d19dbd25cac6dd6b0f4c58b8.AAID': 345,
 '000c535203a6e7905cfd96b2776e4794.AAID': 346,
 '000c5618b5ec5789b383201a69828f8c.AAID': 347,
 '000c61605d746fd91ee159075a7497cf.AAID': 348,
 '000c63b6efa2f8e6eaac1f72be896ae1.AAID': 349,
 '000c6d1416a59df388edc0a10b96b570.IDFA': 350,
 '000c7bbb373a3a377e662db8bc89813d.AAID': 351,
 '000c89da6f8b7d034d6c07d95ede9ad0.AAID': 352,
 '000c9e37b797a96f7e43ef69be67e9cf.AAID': 353,
 '000c9f62f474ec263ddeebc70f4c6712.AAID': 354,
 '000ca64b97a0530f46341d55ccc9f3c1.AAID': 355,
 '000cb59af06207e123f692dad07ee6dd.AAID': 356,
 '000cba9d4811c588cbbde5d987083bb3.IDFA': 357,
 '000ccab457317efd75a6d461625a0b00.AAID': 358,
 '000ccef31f98643c88dfbacfb69c76d5.AAID': 359,
 '000ccff62ac765c4b6f6f93e064efa7a.AAID': 360,
 '000cd7df41719d6c7502c52fc0b1a167.IDFA': 361,
 '000cef942cb498da0ee7bc6c20f2f765.AAID': 362,
 '000cf6c102da77c5b102f9b95e513fa2.AAID': 363,
 '000d18613fb0d25b84f10d12878f4282.IDFA': 364,
 '000d1c85ac6c4e4c49d8bfda9d766696.AAID': 365,
 '000d29fd91c3f4c9b29a119f2c6dfd61.AAID': 366,
 '000d43c998ca8c940e4cc8a373ec21f2.AAID': 367,
 '000d57f1c8005e2218a3db37ff5372f4.AAID': 368,
 '000d59e2d68049731054a63e3d9811ed.AAID': 369,
 '000d6f2ba7adbb9d0e939fd71f99c126.AAID': 370,
 '000d77364188f1911557bde13d46fea9.AAID': 371,
 '000d8143e8824f5096c58eee05b10fb2.AAID': 372,
 '000d8642679f979c4653d8390a2543e0.AAID': 373,
 '000d8b770a056f410d02e433ba95ee9d.AAID': 374,
 '000d8bbb8dbce44f30fa29941b1318dc.IDFA': 375,
 '000d9027262947d7a349efd4949d7c8b.AAID': 376,
 '000da56a3e5b9261d8643e7e9f6636e6.AAID': 377,
 '000da742fbc32c99da9e480173a9a43a.AAID': 378,
 '000dbac9f257d2c4c961ef29d2d66109.AAID': 379,
 '000dbd7d340d62229f6cdd7cd7e3b06a.IDFA': 380,
 '000dbe3daf191fb08b283f0eed32f4b3.AAID': 381,
 '000dc1d388e45aa44a456a3a0e14c614.AAID': 382,
 '000dc6d72782deb9d0fd632f606ef28c.IDFA': 383,
 '000dc77234d4e7ce21eb262eda885311.AAID': 384,
 '000de179e28d4a3cae009c932b79baee.AAID': 385,
 '000de27983559db4638b7b10b83e8adc.AAID': 386,
 '000df3150804210e8e9744e95a2cad08.AAID': 387,
 '000df6d979ef469be38e39da1b79b7d1.AAID': 388,
 '000e14a3eddc352898b68881d8adbc88.AAID': 389,
 '000e21b1b96256e12c5235a35450385e.AAID': 390,
 '000e25539d210b56798bcd1491894f34.AAID': 391,
 '000e2f1cb72ecc982e1fe172f84badce.AAID': 392,
 '000e35537ec281bd04a91c9410bdb4af.AAID': 393,
 '000e409e9ee3a72ecb2906ba6582a5bb.AAID': 394,
 '000e43976a9b8751bcac2505ef0f7489.AAID': 395,
 '000e443e359982f911592300711d1ec8.AAID': 396,
 '000e4c78ed6a31f942795f957119806b.AAID': 397,
 '000e585752ee97a4e800794003b74b4e.AAID': 398,
 '000e5c7412b3db998fce445cd2d9e065.IDFA': 399,
 '000e5d91db0a625d3230df78db20e496.AAID': 400,
 '000e5ff9e678ab34714f0b4c839baea0.AAID': 401,
 '000e798ee078ad7e882449b90f551422.AAID': 402,
 '000e7be97d998c393415f1cba07d9bdf.IDFA': 403,
 '000e85730ffbf67383caf2b2b52cefb4.IDFA': 404,
 '000e8c8dd87b134b458a51fcedf67b44.AAID': 405,
 '000e95b4a15d65f98d30dba014e0c64f.AAID': 406,
 '000e9724679d9a3d3b5362991e2d3107.AAID': 407,
 '000e9b0ab773b7d35524a629e680edb1.AAID': 408,
 '000ea2714889f8625ecd90a6aea6df8d.AAID': 409,
 '000eae9a3b78e41db614c27a67f62beb.AAID': 410,
 '000eb18022d9028057d1a2c92f12c205.AAID': 411,
 '000edaf5358c12171e75522cb2f45c12.AAID': 412,
 '000edd2ffa4a3c6a9f48a5571a80060f.AAID': 413,
 '000ee0735429f707c71f65b0d4314bd3.AAID': 414,
 '000eeb91355064c387728d689ed6f4d4.IDFA': 415,
 '000ef464e6958c46e72ce6c44e12301e.AAID': 416,
 '000ef4ff97ee93ccef491e2ca8bf55ac.AAID': 417,
 '000efb258fd08ed57ec698f3ed191988.AAID': 418,
 '000efd4d3e236ad2d07fdd931a968467.AAID': 419,
 '000efd74e3c2a80f8f072474c50376ef.AAID': 420,
 '000efddf8188c3ddffca996676d00bba.AAID': 421,
 '000eff59612a5ce95a82c44f3bfcf208.AAID': 422,
 '000f018db29c48881c501aaa15cb035a.IDFA': 423,
 '000f09e8224febc064c26ea4b4f34fd0.AAID': 424,
 '000f0e2cede5bd5e4bfc13d999b890e6.IDFA': 425,
 '000f2f97b048391894ae7167e691a5c5.AAID': 426,
 '000f3f542240800ee2b4a5fbf8f5ee44.AAID': 427,

In [ ]:
np.random.shuffle(ids)

In [6]:
ids

['dd2ea3483dfc01875cc8b96099551fca.AAID',
 'cae61196349756f4144dff90988950fd.AAID',
 'ceb2d062eba761819305dc08869b4888.AAID',
 'cf9d2de90007f351e1910aac36098db1.AAID',
 'f1e0b4af8965bd7c19bae77bf825954f.AAID',
 'a7d8b630b97b73eaba7449794f035eea.AAID',
 'cb4e73c67cd0a0e34bbcf75b99c5aeb5.IDFA',
 '8aab1802ea5fea32328c3e3cf4353653.AAID',
 '660dcf2388cb47b1b2710fd69fbf3ab5.AAID',
 'a75620592822566f32266a42d83aa61f.AAID',
 '4e8915fc978c2e5f9eb8ddaeee71625f.AAID',
 '5ea9be188fc81fcad1e200e004adc9f2.AAID',
 '23b1b84c0de024b5183608fc55580eba.AAID',
 '7306ee677ec51158014d69adc5432154.IDFA',
 '67104ab972e66c0ef1034d2823ee5e39.AAID',
 '82953df2dfa194334f6fc1e87a714e42.AAID',
 '4b8b0c40e17e2eb73d4dbcf2a20e52d4.IDFA',
 '5f4b401fc67f8d80067d0280e33363cd.AAID',
 '5145111bdf5af90aebf6cf76f1652b7e.IDFA',
 '87d84581625a28c6ae4fe689237efed2.AAID',
 'cfa5544387949454e9ba73cbe05daf1f.AAID',
 '7ace097551a1ffe4fddc4ab1a213b1ad.AAID',
 'b1910c118f7f7b876929b7d5d17918a3.AAID',
 '520c3f9b018ad70314b9ab1bdfab2513.AAID',
 '9e16565ef4a0848c6231f166940a5604.AAID',
 '0ad40f3c369cc36cb9fac695ba1a467e.AAID',
 'b350695e9a4cf574ce3967545d540f11.AAID',
 'ba97c072064836c73423898b84c7be51.AAID',
 'f00bf5747b2f3f2250e088f865ee2ab4.AAID',
 '72c08515fcdf2fdcde0ae3bfeacb8fe5.AAID',
 'a47a870a51d5b85dd231d52a0ffe880d.AAID',
 '9ae4fec3530d95f57888d96d0c5d5a87.IDFA',
 'fad41c5fe20720f40caef4ff5432d9f9.AAID',
 'c0bb1d64959054805699a1ec308e3993.AAID',
 '3be76bba05b3d1d2a9d0d75803b8b298.AAID',
 'd5a6ecec7d463874dfe82912988151b8.AAID',
 'c29b38c522d5ec93f42f5077da1e4273.AAID',
 'c989dbadf8c3ff3e03e8b05926cec015.AAID',
 '7d898d1c31b37a7a1bd86716c3f10435.AAID',
 'f3d50aaf63c141ef2c46b872ca772e6b.IDFA',
 '41f5238a4018b28c7a88d7bc478a6468.IDFA',
 '0bca651efc104a24a708b8350def07ce.AAID',
 'b69ddbe4a2a960d60d88c2bd5ca542a4.AAID',
 '3da53bc3b0ba2374e637483359ac04f4.AAID',
 'eddbbd37d399eddff879220a05711cb4.IDFA',
 '98be8319250849edf164a353d90316cc.AAID',
 'c014ed43cbcc70cf1b64ddea5e5cb52c.AAID',
 'b46d0ace687ec13be756c90fd1715149.AAID',
 '272aea645f2b9fde7c26c0dec31add40.AAID',
 'ca10149d0d3dd2b9a4a4a944e161329f.IDFA',
 '224fc4a15bf94d1e314be1684b51f481.IDFA',
 '2ae55e97d55386697382a5a3a779f6ff.AAID',
 '7d2dd26f9958920b64f1851f1ba94d13.AAID',
 '6f8018745e039eb5b5dc95df1308ecb0.AAID',
 '4c1d90eeba2c8a93ebb97a928c5e7f86.AAID',
 '80e7d61a9f7c8352c32ddc381a3b1676.AAID',
 '791d4aa39553e88e93906ce9cb79459e.AAID',
 '38e23f16db14b2d45fedaa9d153cc65d.AAID',
 'eb68f74cb845d679828a1a3e43b04af3.AAID',
 'ac2e2a594c609d1f5bd0caeb6be82a72.AAID',
 '29876bec117a4f049fb42b9aae1298c6.AAID',
 '7c5ac9c126d58fe6717058118520ec86.AAID',
 '4c2f736c729dda7fa65b0a0b52c55892.IDFA',
 '36dc17d0b05917c3b695c82ed2981bd6.AAID',
 '2e998615daa44eff427a457a4af7846e.AAID',
 '29006fc98aac33a5f6920b0548dd8fc7.IDFA',
 'e34b76ee69997c98412b7284e1c01030.AAID',
 '83d59b1db82fe93e87eae3a46ececf2f.AAID',
 '0be0ec0f6e465849a3467dd7ba402e8b.AAID',
 'e45ecf55d2e0ef2bd6e9f4bf27f962b0.AAID',
 '9237cf4936b763947c9e103cda41d7fa.AAID',
 '416c925e50885b63de0f8edcb893b86e.AAID',
 'a554f71cfc710e3d951ae4cd2bbef5dd.AAID',
 'dcffa5992c63b4c7efc88e6d5ebf892c.AAID',
 '9af3cd30ae08cf1152d98c8e25e96d1e.IDFA',
 '18136ee9f41d20921ffaf34228cf0c3b.IDFA',
 'd7ea99a99083cb1b7a959a5a77f15b0d.AAID',
 'b8d83d896a13d59ff84cd6403866b4a7.AAID',
 'b1c5a39a2031d6888698ad15174e0836.AAID',
 '2371688ab52417245709ecf3673891dd.AAID',
 'c4cb725e2c5ee289b5863b7d85f4eaf7.AAID',
 '55e4bf39e7d9cebc6d290573bbfe6342.AAID',
 '1d12d207c29cc6e429b39e4671313a99.AAID',
 '046b8d1bf788644cbc12a2ff0231c1ba.AAID',
 '8fa31d8fe4c6e0383f69833115aae970.AAID',
 '72423d2d25f25f7ecc7df406cdeca0c6.IDFA',
 '8380da336d68cf0ce02df3a2774e2f57.AAID',
 '7dc98b45c7142cf3f390e4d92c743ea3.AAID',
 '4ef82a6f7bff60c0fd1da7eff2d22bf3.AAID',
 '819335cab965c990cdeef0d81dc485a8.AAID',
 '85bc014518ca28debf3af860540829a7.AAID',
 '3e88cc7171f0fcb99f9929f755fa77f6.IDFA',
 'b07f2f5e9aab666ad634c906cdf34be9.AAID',
 '414898c33975acfec027347c2ab3d815.AAID',
 '0257e10643892951f1c0533f3daed1ed.AAID',
 '7e50ccf4b5fe89cb2023b68de7b14f53.AAID',
 '9a2c6fafc17923e7273985269fcd0303.AAID',
 'cd69750dbb682852a1c3236afd0d4b3f.AAID',
 '2e861577250579f90f35356460b64876.IDFA',
 '3a7ffbea98628e44e369b8d21f8abd1d.AAID',
 '3101beb35d84821e4bd5ba997a992f2b.AAID',
 '225c78c66a33feb0136675c0343f8dad.AAID',
 '90f4b3e80ebbcd06649a97e07e29cd9a.IDFA',
 '2cb610a54d33a3e624868afe239e388e.AAID',
 'facbf781f747783dc76b55fea076733e.AAID',
 '90ab909a17025cad6f83fcaf8758dfaf.AAID',
 '1f65b9850018980ca389f06a08217f42.AAID',
 'd0d9f556cfb9f875173e068f20dcab97.AAID',
 'a672d983e2a1842da61b9c5c45bc9260.AAID',
 '62624bf9d72af7d185fe58e74afae7c3.IDFA',
 'b8a661cdad33e4f541dedb9bdd00f3d9.AAID',
 '92e94f0b26e7b5cd9b82588e48873f70.AAID',
 'a33fbf53e24fe9004a8e3ee2da039162.AAID',
 '4956467da49077ef11282abbe16bbf97.IDFA',
 'ce89fc1237d7c5362ed029704ffd0157.AAID',
 'a81395f8ba893c26596aa53d2e089b7a.AAID',
 '65b78095724f3d154d19e1a631239294.AAID',
 'b2281d93f46296e1c1621b88c027463b.AAID',
 'b3cd8cde5a5097abf158dd222367a8d1.AAID',
 'fe93bbeeae796fd77c0d6236f0c02b85.AAID',
 'beb3201365f00e955b89803005be7dfb.IDFA',
 '3af2138439fb1e8c08e44875a646e884.AAID',
 'cb3d0fe935dd1b52abedd4e6b489d85f.IDFA',
 '3ebbee78cca358dfc9a15a25985f51c7.AAID',
 'bdc01a689fb54419d13623da44386d1e.AAID',
 '6f04d6f0073c6991b88437c8f88c8124.AAID',
 '06fcb4c7458bd6f25ac6a615437d4c64.AAID',
 '0aeb54d003ef303a1745f89d87e49ea4.IDFA',
 'f83e4bd342e7e236cc1bdba77ad6e7a5.AAID',
 '9919e1d2b74f124de4adc0f3a76e8ea6.AAID',
 '80d4de46f1c5b296f9e2aa9a539516c3.AAID',
 'e079f00d8c6c8a6ef87779f967601d5b.AAID',
 '4d476579d73b25f414f0dc692a3dc9ab.AAID',
 '6057ff95afbe1157191bf995037c8864.AAID',
 '22dc2243efd019e44fd2dc12f7c351e2.AAID',
 '7c210a28ff7ebf529267d69986b03c72.IDFA',
 '5c8ebdf760330992a2aeefefeab60a77.AAID',
 '820bf3252bdc29eda7bc5fdf2aef437e.AAID',
 '186d7ea36a0a6bdfbe0d0c5acb96f9a8.AAID',
 'fde175efb58fddfad61a6406647c8547.IDFA',
 '5b78c85a2455f36e45e186cd0cc64f86.AAID',
 '3c75f228cb9e6181fd41127b4aeb2b63.AAID',
 'b9fbd6a3d910e18d81f97fecc85b2d8d.AAID',
 'cdd3e68b3b1e61cf668d7a310d0b72f9.AAID',
 'e92145938b51080a6d5e13fdc591edab.AAID',
 'e6722327d83173f393559d180f4f5d22.AAID',
 '32002b18b0fba27e7d84f22352472974.AAID',
 '745cc0b2ead1e4eb4acfba82e8b65e0d.AAID',
 '11e68262df793e959529ce97c9697089.AAID',
 '166b8e893e9aa30f6a68d80960adfd20.AAID',
 '2f126a8c934f3316d184d947e870666a.AAID',
 'b9250ff229c63f663624e9c9bb7322a9.AAID',
 '75a9c02be3665000eb49145f8dbd6d17.AAID',
 '7d63f0f4c9a64f12b0107da18f2d4369.IDFA',
 '7422b79b5c846b3eb0d317315835aec8.AAID',
 'a0877dda39eef983e67f20461f35b41c.IDFA',
 '947cdf1d0fe6e04d4c6fc183b35f2568.AAID',
 '717b9ffc5e4f2c986f773888c6ccdc69.IDFA',
 '12b1d44e46aa5bb7e63ee84233701bc3.AAID',
 'a7b521e566b5a7ea3088fb11c33d0754.AAID',
 '2702353b06a34a532c44aa8249036df9.AAID',
 '7ece1dbee541ea3fb714ee84c4401904.AAID',
 '0473c8e21477438cfecafbb8c7057bc7.AAID',
 '7916dbd9e9967e79cece304b1e15d4c6.IDFA',
 '9c218ae3d1834b95bd7ffa90613bb891.AAID',
 '496019b6542fe09c5d0b90c730ff34f1.AAID',
 'ac1612391a87dc9463ace7cc95ad9948.AAID',
 '66fac7edac4aeef91589d40627a80617.AAID',
 '4fc4ced483ffba0b6c85a5bc4dce2e17.AAID',
 '9af33610ff864bb3c35247de74a646e6.AAID',
 '529126e1a778b995ac52af71e20de89c.AAID',
 '52313f58eacb1f5b852cb3bcf95de47b.AAID',
 'c18a9834b95a2b7b121e580105202e71.AAID',
 '7b77bb0945e7a7a93c469df65beabb22.AAID',
 'd096243068d4cbcd87c0ce42c24a09b5.AAID',
 'da487d13bdaebd885fcf11a95e78a5f6.IDFA',
 'a56e4644075f4c801fc5a2dccc7122c9.AAID',
 '24633b414ea6585ed9df60a10b80e0d4.IDFA',
 '185bb3df1bee8c15808c489c7fcfe475.AAID',
 '60aa3578c0a135500daad81cbbe46c77.AAID',
 'df0e3743a7c97e7dfcb35ee37f32bdbc.IDFA',
 '7b68cc2f0861c366f89504adafd31d9d.AAID',
 '00e9305e577227a731a1e5dc1f8fa1bf.IDFA',
 '159b89cc2d558bc0ea0229dd4e49cfcd.AAID',
 'f39a537e6a4460976fa4bfaf36ef171a.IDFA',
 '8456c05e948566f49bddb20387c1f11a.AAID',
 '28f3ca394fa973768b6757aef8a15bcc.AAID',
 '4124f8b67c1b958022ad29448848d824.AAID',
 '1d458a0f8732a6dc57c3a39de80504f3.AAID',
 'b9483a50f170d0421bfe9cff8dcd1146.AAID',
 'd12f25907f36a2b5afea251976e4013a.AAID',
 'b4acb4c2efdf0907cbaaf6fa532b9619.IDFA',
 'dc769192c4bc7ddd343582bf4c4e098d.AAID',
 '39cc3863d0348921894f99e7f17422be.IDFA',
 '2ddc8d93aaa28f367918eabb2125d0e9.AAID',
 'def8c6086cbbd417008db418febb655f.IDFA',
 '55f737e26c2198e5b833f364742b1bb1.AAID',
 '54c1eb770fe15d60535a207ce55696a9.IDFA',
 'a1728814661e7388ff3c31088b0b2b08.AAID',
 '8ca2d14999d88c7ff829e8d6a4bb36a0.AAID',
 'dabf7440997489a3e02a8e985a0ee312.AAID',
 '6be7b839641783b20ac4d2fbcbf46713.AAID',
 '3c8faf1d5f800ed687cdf1a6410274f3.AAID',
 '277f2625cef63e4061b1bb6d4e6c2468.AAID',
 'b9354b27732f490ab47a815e7553907a.AAID',
 'c4e136d57f0183208fd16dce8ed3ba60.AAID',
 'a09892725def5a2bff27499174f4c09c.AAID',
 '63f2e0e745d6fb2f7299d6739f17631b.AAID',
 '4f7b76e17e54192c0579c6d1263cefd1.AAID',
 'a1f682f570ccf628ec7328b6805f4817.AAID',
 '4bca9619359c94000a83aa0f1d403343.AAID',
 '4f8aaadca128b1457ca07b8c6a480fba.AAID',
 'e995934f8654e9b79a7a9f64da1e3daf.AAID',
 'eba62906f3cefcb0fa77c159f940b9a9.IDFA',
 '37dae5f808097ab1a7e2cd2f9ccff968.AAID',
 '2b404fc6cab705c97baeaca2109eebf6.AAID',
 '728d500f7d1d45e6aa4efd8c15080b57.AAID',
 'd3abd2058dae00716d3b5a2518a9950e.AAID',
 '7a57f2169110cb6783dc0e379156cb02.AAID',
 '6a3ad667cda45093f336bef4b69b7164.AAID',
 '67067b03df655ab23dbaaa6372b3b723.AAID',
 'cc120aa511608c42db0a964c9de08fd6.AAID',
 'a0cb27c03ffb4530d434a2f777d7d867.AAID',
 '6e31f90e08df9be92d16de7ba3ec4bac.IDFA',
 '43127710cb74b37feae5dda751853dc9.AAID',
 '62ed585258836e8f74ea59377cae975e.AAID',
 '888e16d8c3ad12a6f70c8cf4589f8244.IDFA',
 'e5b64bcb147f69e5c91b69ee1bb8c62c.IDFA',
 'fa79c6f9ad4f566cba8c2a29765251ef.AAID',
 'e1d3d5cc5aa37acf8b9db4fd4749be51.AAID',
 '9ded69c738938f1aa216e92ca316baf3.AAID',
 'b2c76485b757777d9f3673d75c5ce71e.AAID',
 '13c0aec9afc88e3e62042b7a2745b651.IDFA',
 '2218d1fa76e6e1e8e763425152d51174.AAID',
 '2bbed52cfa37b926a7d133f94a1eb6b6.IDFA',
 '2ce92e77aec32f2d88d9d04c65f051fc.AAID',
 'cf7491dfa9ab8131619d38ce9765a20e.IDFA',
 '4d684b8a17995a4220dfe04faba40cb9.AAID',
 'b01fbbce739622154ae5f10e276eeab5.AAID',
 'b8ae8449c84bde40d86a419e741b743f.AAID',
 'a6962a68e230e2671fdaab6d47a9b096.AAID',
 '0cb13a391f096d32ea91214b1e5b8ff7.AAID',
 '4ad9abc0a776aff29ba2f73189effab9.AAID',
 'd96662b5e5bd649a6daf8e021acd5233.AAID',
 '98906ef182a912bc8a7fa598ce371a05.IDFA',
 '618fecbf51ced62944e2eeb5f9bde207.IDFA',
 'c9b2198107443807d8cc8fd370fb7ff6.IDFA',
 '15caca23096aacb15eb16461a0a917a3.AAID',
 '0a8663cb87e944c557fec52bb7fd4d73.AAID',
 '1dc20f052a77380f69e517e19eddeb04.AAID',
 '3a0f8735163f9e49795af4f595b32d26.AAID',
 '5fdb205ad598a37490d8ca4de02b5a59.AAID',
 'bb637884b9fc37696bd450cbd6a65034.AAID',
 '8da51bc88dd6dc8718dd78b7c50bb4ad.AAID',
 'a7688d4771868fdf644e03f462982ba5.AAID',
 '4edddc3725af50247001de9710af1327.AAID',
 '1e7d42c06abe35fc8bfacbf8b0d7f8e8.IDFA',
 'ffe21224e8ed337ed7a7122caef23a29.IDFA',
 'c5cf6a0238c6241b3e32bff7b730c2b2.IDFA',
 'a79425a30229d2768eef035310ad8b86.AAID',
 '9521c11cb0bc2e5adb70f13f3bc9106a.AAID',
 '5e1c08b757b05008dbcaf57b10689d41.AAID',
 '0da615bac24752693cd6954e36a54b52.AAID',
 'ccfc9d9b76fa8c1b17f8f834a9b6d292.AAID',
 '8ec08acb201b7d1080377eac655c3275.AAID',
 'bfc102f437f95c1d28f2a179946a0829.AAID',
 '6a70d8efb1a588ca2d7b43e04730061e.AAID',
 'c3b07e1b1a184337e656176ac720e7aa.AAID',
 '844d8c2fa4f4af93cdbc65c56d0775fc.AAID',
 'a310cbc088f5791b4942a6911b3748f7.AAID',
 '2123960085f68565e6a2303dd5b186c8.IDFA',
 '93e22ceb6bee9ffd956cd273792c4be0.AAID',
 '90fffdc93f44fad18608e5762cc0a035.AAID',
 'fa8f7c46858fbfa63332ef6e54202ddc.AAID',
 'ba3ce114e2040eef9401db5f2c533f88.AAID',
 '76f27ec7588404e915e42e1c13154313.IDFA',
 '45704b67bbccd21709bce814947dd9b7.AAID',
 '2588242c120abb0323c34cdcbe9bc24d.AAID',
 '75a6e24138a030e619ab503b077d9fa5.IDFA',
 '1293a9cf130ab063c83e4e71fa327890.AAID',
 'd74cce4e169207f360cd49370987473e.AAID',
 '1f805d2813952a995457baf129a42f26.AAID',
 '89a9a5e9fafc2f891ddcb0b3e44993cb.IDFA',
 '5fec5bf488f79d5eaee037a54299adb7.AAID',
 'd7bea12c895dcbd6c867ee5750964ae1.IDFA',
 'ba921e5f9bbcec10b533cd7741ed7c2e.AAID',
 'c489f50aed889bd28f125297d38b3904.AAID',
 '50865797e40ecb6e762429bddcc2bf43.AAID',
 '42c01e2efce3106465d5e6e253ce0a7c.IDFA',
 'e0ac9a944a831e0b121f24f258c8543a.AAID',
 '51419e252c3300d5e5098eadb68a9211.AAID',
 'add941c54510346acc0f3c31c87606b3.AAID',
 '23e57920f41ac091e66d9f128427f77a.AAID',
 'a29500c95e53534013eb9cb15c485a1b.AAID',
 '0bb61543e6e290805dbc76a6851e102c.AAID',
 'ac834a003391cbc659c8a384bfc34d1a.IDFA',
 '67d05802189a7cfad1340c16c85cebdd.AAID',
 '7c64c3d796b7f0d235810af13b03dd70.AAID',
 '1736461443e472a69cf8a12b58ad07b4.AAID',
 'bbe0dd6362b6432eb584385e71758bb6.AAID',
 '7ecc7516dc9251e93ce6d657b548d3d5.AAID',
 'c5f87fa7f9090e9b9232ac860378402f.AAID',
 '207899b15434f2e8b48b48e851b2bc42.AAID',
 '71a3ea5a0158357059ad7f05c711efba.AAID',
 '6830fa9bf67c788cf413808ec7b1be2d.IDFA',
 'c5e95765bf4c962210ceef9a928c1052.AAID',
 '67b926a4e69014e62591ca81affdd072.IDFA',
 '9ef45f901dde5ee553d305a86a17e593.IDFA',
 '1f6025988a59cba9ee391b3a7426b95a.IDFA',
 '7a7513c4ec34a194965c2c983e864e42.AAID',
 '6bb637d403360becc1ecdf52fecee070.AAID',
 'd4f5bb7db651eaeed8ea19d70f612535.IDFA',
 'e28265cb9dfc4ae4db798eddfa209dfb.AAID',
 'ac34dfa265e1c460a16e36a18df70fa6.AAID',
 '234307e590871e4357f6834472b795f7.AAID',
 '62ff2b73a06558fbda2e6125ac465290.AAID',
 '0f951737f17a320ac4df63bfe62782e9.AAID',
 'b437f34cf4cff12f0df0fa5461228142.AAID',
 '7dab53fcfba5b8082ab938078013f827.IDFA',
 '9ba4c333d6c2402ee2ada8d7a50cd60c.AAID',
 '68364efffd6048de3c01cd67524777c4.AAID',
 'f3e45ae6a5319fc9145d1ce92e5dc175.AAID',
 '5928cc52b7b76ec0f2a2cfaf9873e1a9.AAID',
 '1e6b98ca52cd7f3afd57f7c74edea7a9.AAID',
 'e312925d9ed2387979caa4ecb40ce2a1.IDFA',
 '6e6f99080917d7a482f444f9b2fd6817.AAID',
 '98c48271066ecb3c3dca3791c1ace98d.AAID',
 '4fcaf0c6d0152698f50b6aab75d9c2b7.AAID',
 'f1b3d7da585bde5f87c6b970c87a34fc.IDFA',
 '2317189408d70f4c66bd2ca2a6395416.IDFA',
 'c04a9240c4f0ab55a2a7eb37c5201a92.AAID',
 'e11956d73130d8001b39d057426b568c.AAID',
 '4da9def6222a53363b4b165ea79e729a.AAID',
 '1755cadab0d2c158a87f133b28836a70.AAID',
 '2e0aafa44f03f2251311f4be3c869b28.AAID',
 'b8b15ad7961752375afaa665c259533b.AAID',
 '820041b4a3a0df2ae760387f6695862d.AAID',
 'd7346c06531b26fae7c85cc158183429.AAID',
 '096deecdb07b4f2abcf8b5a652342c5b.AAID',
 'a3cdae2c01c01a505e09fea938ca1606.AAID',
 '27349fe1b26f1bd78705344ba16004c6.AAID',
 'd76177a99d5479dc3fedeeba1873293d.AAID',
 '4f7bb1c6a27113875e9de22630dae475.AAID',
 'd84b07c11ed7b97950c3edb47d330be6.AAID',
 'bf60b5ed17a55d9b698674a5a822060f.AAID',
 '3f41e545502d3c5b9626a087c5957d7a.AAID',
 '9e65a7e228257ec6af5c874e023d4fae.AAID',
 '67b0b9b6955a30aefcf066a820d9abe6.IDFA',
 '7774543a066c9d315bf7bbfd6cf2a1d4.AAID',
 'd58c6982dd69f63ab440b7199ad559f8.AAID',
 'b9648fd9ee6f46e590cec87ad250dd97.AAID',
 '11645df61e0a4b289def234ba195643a.AAID',
 '89f4a2e45dff6e2f6c5447fb206cd0d5.AAID',
 '40c40b1c5e6f4be0afbf9e2f07076b0b.AAID',
 'e51755e928e169b059fe02329b7e6c9a.IDFA',
 '4050ad0b1d42d9e3ec6c05003f4a7dcc.IDFA',
 '1f4696bb131ae358c18bc3284bfe79f5.AAID',
 '1c1825ca5f165566c5f01eab8e1a2b89.IDFA',
 'ad40298312ec21cdaea5f0c9ced0258e.AAID',
 'abc05f9d99a4e8c8fce41e8ffa4ecef8.AAID',
 '7aab2d32d2987a32ce5ec709b2134695.AAID',
 '54118af54e6101a512a31d4f6c77bf22.AAID',
 '7ae0201e8a9f4c64fa14624d89fa123f.AAID',
 '0afca7d3b4b34aab21c9b83ea1f51b98.IDFA',
 'cfe019f75acde87681a2a62a7d7c37c8.AAID',
 '414675390067ccd6e2823735c59ec01e.AAID',
 '4218207a589c3139d0b5fc318ee9fc4d.AAID',
 '2a7dd12ab45dda122a29fce90528aadb.IDFA',
 '891ea0c4eab7e512ffc48a6106303c2a.AAID',
 '6a0fd7d9aa376990a72f8c0da04c8c8a.AAID',
 'fe867a94b1b2f13084b02cdf036b2892.AAID',
 'c09c43eed8d19e22771235093b865f36.IDFA',
 '19e189cc588407048764dba9ab8d860b.AAID',
 '77cd64e67251e2a86b28fc9c7d2cb954.AAID',
 'e63f22ab30b07cf1955e8f610954e9ca.IDFA',
 'b1c4ceb3aa4cf61cc3ee35ca734a1c30.IDFA',
 '269813777c34ccd7d0e1f7a6de1e4e57.AAID',
 '6ab3ee614e411cf9bb025e3341f3980a.AAID',
 'f3a12f068a34ebdf0fd1f5ad4751e229.AAID',
 '50c9935bcc2f3194f642715aa45a6e40.AAID',
 'aa754a03fdc3bd660615db6d8cdea3cb.AAID',
 '6a30e4e0bfe149b8ed6c0ac9bf6f2191.IDFA',
 '8c51800e4773e621a4bbd5e651f821f0.AAID',
 '4e9801f9dcd0f04b9ec768ec0084334f.AAID',
 '5ece4199c8b75aff940e539ebe2f1fc9.AAID',
 '0b2dbb119dbbadef5bc0179c6ee9d40a.AAID',
 '9050980dece0c3728339e306a5cdf249.AAID',
 'bed6ce40b5efd6eb96991da36de5e8cc.IDFA',
 'a6b77a07d62bbb5bd68386f7985e4c16.IDFA',
 'be94f5d329f47e373afb885ded4d1793.IDFA',
 '50c6ea029261de38334a39636b23ca95.AAID',
 'f70a8d27f9de9adedefe5d6b2c0bac90.AAID',
 '34614b28bf73368737bfe6aba44f2109.IDFA',
 '1385b42330be90565fc7219f21553dc5.AAID',
 'bf443f06eadead76ad2755c29b84155c.IDFA',
 '1a7f9d5d07f3dbb64d4882ef87d55297.AAID',
 'e487246bc6c72562ec0195812e6eccaf.AAID',
 '60a3f7ac3f2d5cb694a5ed44a11c9016.AAID',
 'd88cb9b64fe82205344466ceecd57f11.AAID',
 'a2272185bb980b607e9f6f07f50a43ed.IDFA',
 '1275732aa6b4340680f7a3823730532c.AAID',
 'e7148630aa3e773ef94fdb186ff3ccaa.AAID',
 'f582ef78b5b20899a27d3c04751c796f.AAID',
 '3650fb0da96cd50abba0e25fb656450e.IDFA',
 '85d6c4afbd3fb5401c68c105b3a0a384.AAID',
 '107149e375cf1da57ca5ecdc040066b2.AAID',
 '8b815a1cc60bc9ae87574773c71f9f1f.AAID',
 'e03f0ddb093bfdd83b02571bdddd95d4.AAID',
 '83c3ac20060a42b70082addbdcf7bb67.AAID',
 '0352d31acb9b8fbbb203174214b4429e.AAID',
 '68bac43a735ac74433a2e942a5ea6226.AAID',
 'f3bbf953dc347892f9863c269f05c960.IDFA',
 'e115393f6e86d0fb71f70a59a15df503.AAID',
 '0fb823865c7cca162c59a1283397a789.IDFA',
 '0ccc84cdd6373471c2f3d6f89ac3725e.AAID',
 'd10ac1143aa5b8bd821a4ea049c7d126.AAID',
 '8d56f53bfae462432e82605a248bc1eb.AAID',
 '3a7e5523a71106d33dfa7f3756c7e072.AAID',
 '1f10b7f6f4a81b7793b2f25c575666b1.AAID',
 '354a83ce4cffb17b070260c34ae03e88.IDFA',
 '87fc87c05e3ad913ff0b5d6fb41c52a5.IDFA',
 '4e941b860b4db86aab44b5dcb57375c4.AAID',
 '5e9b8ac10d34e3797c6b4f52f054b83b.AAID',
 '75ecb78c02c0c111e03450d3108815ab.AAID',
 'f057cee2e68687fe8394abd2d9814298.AAID',
 'baebf11feae43f4730e6d89ad7a6c358.AAID',
 '03e1c6071a8a58315525e07793717a98.AAID',
 '8e24279be64e2ca55089fca389213d9d.AAID',
 'df564fe401ce51324df6091bba844bed.AAID',
 'bdb21353123a8a24818b924c0e4dcdbe.AAID',
 '7837474639c0f68fb6089b88f9098739.AAID',
 '4335ba6ce5be9840f02f95ee871cb82a.AAID',
 '8b4626ac125e0a17732e462c79930865.AAID',
 'bd3dcf05b4f63c725001ee89d7aaf98c.IDFA',
 '0b85430008ba58d6a571fcdd88e09b75.AAID',
 '91e27603e5a826af5c9a9db7a078a808.AAID',
 '1383f60e185f7a26aa85a368b35c2c9f.AAID',
 'd7242d2fee6d0d641ceb97fe59ae0b37.IDFA',
 '2080c13a64f64f9202cce14b7acc1b06.IDFA',
 '638ad53c0f83d650bfd368b68041e03e.IDFA',
 '84c8f292509f33b33557f5bd91075f22.AAID',
 'a9964f2b10375c44c4585c42ce695bc4.IDFA',
 'bd4e3d86eb94992f0796c3e15c02bf7e.IDFA',
 '7152540db09d81175337e5a520fc3b66.AAID',
 'c2871a852688e75d108b8d095407d17a.AAID',
 'a66e6505b7494d5c10a0716babc203a7.AAID',
 '8453b912124d57efa7a2bf149b48a698.IDFA',
 'b78790815d0e2256cb5afb325ded25f1.AAID',
 '0f8d3c2c15cf52f63acf73d519327aef.AAID',
 '0f985a19cc7046759e4b3a2a9dc763f8.AAID',
 'd7c65c6419b6369ead7d025f540eb7ac.AAID',
 '0eb85bb8d5712291f7363624be47f2f1.AAID',
 '9d20d67e93e5695897fcd4741b0ed4ba.AAID',
 'a9f359753d0f79a4e608b357670610f3.IDFA',
 '5f2ce3378761fa8ecf1ac55de4681398.AAID',
 '2625272f502a62688d786bf050463797.IDFA',
 '59580056d0792af2e816e3ea285d8a4e.AAID',
 '08153271d4b4b2a136b1e1e572e9c758.AAID',
 '7175c8daa111b94faec5803f401e39b3.AAID',
 '2b5872bf11f96d621608986625541a2a.AAID',
 '6ec5274e04858747455c772738f8cfd9.AAID',
 '70cb6a25a5758ae91c3cffe2da5f0210.AAID',
 '9ad7c29c381873713910f12415b1586a.AAID',
 '5be11799d5c3e3f6d30806385dfa9373.AAID',
 'a9ccacd472ab4cd50b3fe005dc2af1ad.IDFA',
 'a8148dc1a04f23a2d1017eaea6b960fd.AAID',
 '8f98ad843f026e325561ba149311e173.AAID',
 'dcd9da036aeeffac66c49b46aaa26436.AAID',
 '31af94cf0d6815f206f4991248cfd670.IDFA',
 'f10b6765af01915925e914714c0fdd0c.IDFA',
 '76e42aeb1da2e31c41dcd18a8ca1a12c.AAID',
 'd19cd12d790a9356590c08dba6cf77bc.AAID',
 'e398c177dd9fcd8bf81a04427efdbf2b.AAID',
 'e0adcc37fb22e833b0df644bca2d0992.AAID',
 'eafdfcf7cf2e4637eb618384fb0800b8.AAID',
 'abb722ebfe4b0be0b0818bb6e6313885.IDFA',

In [20]:
sorted(ids)

['0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '0000051fc26276495c5a9ab1753a70dd.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '000006ba36dda4e4fe39d406a1299b67.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000142bfd04443d8461e7613e4f600d.AAID',
 '0000278addb0b7cf048517051ed3f688.AAID',
 '0000278addb0b7cf048517051ed3f688.AAID',
 '00003395f709c02f5ddad2eff4d4bfa2.IDFA',
 '0000370e6272b18907fde190edd5c728.AAID',
 '00004246bf0c7f1595a05eb7e5f3fdc5.AAID',
 '00004246bf0c7f1595a05eb7e5f3fdc5.AAID',
 '000052a8dbca773ddf5257da94247d6b.AAID',
 '000054d2c890c308b0649cfd70f32b68.IDFA',
 '000054d2c890c308b0649cfd70f32b68.IDFA',
 '000054d2c890c308b0649cfd70f32b68.IDFA',
 '00005fa780b24932682f16b31a5c69f6.IDFA',
 '00005fa780b24932682f16b31a5c69f6.IDFA',
 '00005feda0bedb6cca9afcecb887007b.AAID',
 '00005feda0bedb6cca9afcecb887007b.AAID',
 '00005feda0bedb6cca9afcecb887007b.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '00006c0dc1e9ab0527385f31f2267385.AAID',
 '000073fd63cab3cf43c34b3f466e2534.AAID',
 '000073fd63cab3cf43c34b3f466e2534.AAID',
 '000073fd63cab3cf43c34b3f466e2534.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '0000752e8d10818f9b59ad187a2a0893.AAID',
 '000086c9027b7ec6809ac71565289741.AAID',
 '000086c9027b7ec6809ac71565289741.AAID',
 '00008d27fffdcef8e3102249c33c93e9.AAID',
 '00008d27fffdcef8e3102249c33c93e9.AAID',
 '00008d27fffdcef8e3102249c33c93e9.AAID',
 '00008f26fbce9c249017e36c850d4e4c.AAID',
 '0000a0688997392e43d0846aeb8784dc.AAID',
 '0000a0688997392e43d0846aeb8784dc.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID',
 '0000a54321512252c9b3362e3e5e0ae3.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000a6824521da23c81d823eb6b61416.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000b590d54908ea5a037096b9214ce2.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d33977a4566504e638592ea15f37.AAID',
 '0000d391434c922fa7c6db139907819d.IDFA',
 '0000d391434c922fa7c6db139907819d.IDFA',
 '0000d391434c922fa7c6db139907819d.IDFA',
 '0000d391434c922fa7c6db139907819d.IDFA',
 '0000d7ead16b81d24db89a02c51a3db7.AAID',
 '0000da197f9a6f6d45f62bd55dcdfa79.AAID',
 '0000da197f9a6f6d45f62bd55dcdfa79.AAID',
 '0000da197f9a6f6d45f62bd55dcdfa79.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '0000e24c4b6adb1c2fc9481149db75e6.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',
 '00011ad382968502b6cef688000178b2.AAID',

In [21]:
np.sort(ids)

array(['0000051fc26276495c5a9ab1753a70dd.AAID',
       '0000051fc26276495c5a9ab1753a70dd.AAID',
       '0000051fc26276495c5a9ab1753a70dd.AAID', ...,
       'ffffec76c36b62f621ac683d6821bb2f.IDFA',
       'ffffec76c36b62f621ac683d6821bb2f.IDFA',
       'ffffec76c36b62f621ac683d6821bb2f.IDFA'],
      shape=(33243659,), dtype='<U37')

In [11]:
np.unique(ids)

array(['0000051fc26276495c5a9ab1753a70dd.AAID',
       '000006ba36dda4e4fe39d406a1299b67.AAID',
       '0000142bfd04443d8461e7613e4f600d.AAID', ...,
       'ffffe113b3e0226a7579cd7e8270ddd2.IDFA',
       'ffffeb51c8daf2250d194a298fbb3c53.AAID',
       'ffffec76c36b62f621ac683d6821bb2f.IDFA'],
      shape=(1652702,), dtype='<U37')

In [ ]:
df = (
    pl.DataFrame([ids], schema=["id_with_type"])
    .unique()
    .with_row_index("device_id", offset=1)
)
# return dict(zip(df["id_with_type"], df["device_id"]))

In [10]:
len(ids)

33243659

In [9]:
df

shape: (1_652_702, 2)
┌───────────┬─────────────────────────────────┐
│ device_id ┆ id_with_type                    │
│ ---       ┆ ---                             │
│ u32       ┆ str                             │
╞═══════════╪═════════════════════════════════╡
│ 1         ┆ 904b690bf6d3c3126f33fce8b7119f… │
│ 2         ┆ bc37e40d19ae9c181bce1f342aa18a… │
│ 3         ┆ 15e0108764dbdaea283ceae0f281d9… │
│ 4         ┆ 17cc7ba914ec2728556094708662e7… │
│ 5         ┆ 8854914818f74ac7f09ffc5a72b244… │
│ …         ┆ …                               │
│ 1652698   ┆ ea6293b7a0ea4b4b267ad16d947882… │
│ 1652699   ┆ 1345b042f26ccaa368225df02b9d1f… │
│ 1652700   ┆ 843bb01398a2c296d6a21ff3c76719… │
│ 1652701   ┆ 734941eb81d2949e8dece8adb99c9f… │
│ 1652702   ┆ 37e89a667129b172754c8109e0beeb… │
└───────────┴─────────────────────────────────┘

In [7]:
lookup

{'0000051fc26276495c5a9ab1753a70dd.AAID': 33,
 '000006ba36dda4e4fe39d406a1299b67.AAID': 58,
 '0000142bfd04443d8461e7613e4f600d.AAID': 216,
 '0000278addb0b7cf048517051ed3f688.AAID': 218,
 '00003395f709c02f5ddad2eff4d4bfa2.IDFA': 219,
 '0000370e6272b18907fde190edd5c728.AAID': 220,
 '00004246bf0c7f1595a05eb7e5f3fdc5.AAID': 222,
 '000052a8dbca773ddf5257da94247d6b.AAID': 223,
 '000054d2c890c308b0649cfd70f32b68.IDFA': 226,
 '00005fa780b24932682f16b31a5c69f6.IDFA': 228,
 '00005feda0bedb6cca9afcecb887007b.AAID': 231,
 '00006c0dc1e9ab0527385f31f2267385.AAID': 342,
 '000073fd63cab3cf43c34b3f466e2534.AAID': 345,
 '0000752e8d10818f9b59ad187a2a0893.AAID': 380,
 '000086c9027b7ec6809ac71565289741.AAID': 382,
 '00008d27fffdcef8e3102249c33c93e9.AAID': 385,
 '00008f26fbce9c249017e36c850d4e4c.AAID': 386,
 '0000a0688997392e43d0846aeb8784dc.AAID': 388,
 '0000a31f8040d7d6f5cd730fbe2c823d.AAID': 406,
 '0000a54321512252c9b3362e3e5e0ae3.AAID': 407,
 '0000a6824521da23c81d823eb6b61416.AAID': 414,
 '0000b590d54908ea5a037096b9214ce2.AAID': 424,
 '0000d33977a4566504e638592ea15f37.AAID': 437,
 '0000d391434c922fa7c6db139907819d.IDFA': 441,
 '0000d7ead16b81d24db89a02c51a3db7.AAID': 442,
 '0000da197f9a6f6d45f62bd55dcdfa79.AAID': 445,
 '0000e24c4b6adb1c2fc9481149db75e6.AAID': 451,
 '00011ad382968502b6cef688000178b2.AAID': 495,
 '00012c23c1ef81bf6f3912bbe64bb861.AAID': 613,
 '0001387e13b731411ff461b94aca9264.AAID': 637,
 '00013dd30f845e8618286c642679636f.AAID': 639,
 '00014538119345c90f616421c422e193.IDFA': 653,
 '0001477976aad52f1e6e29ffc837a283.AAID': 676,
 '00014aae8b4854aae41d0f4b8f8322da.AAID': 688,
 '00014b712020806547dd406c6ff7c3a6.AAID': 741,
 '00014bd600e2dec25af8a073e27c15db.AAID': 765,
 '0001595ad1bb498576f1d20e1c0ffd42.AAID': 766,
 '000159f8f4dfb5d8c4952d23e08f884b.AAID': 767,
 '00016b388656b3765fa34646840ec51a.AAID': 768,
 '0001852c12c7af746be15a824beddfc0.AAID': 934,
 '000195ab6c3758b5c1f8bdf563229bfa.AAID': 947,
 '00019a3f2e8e70b015a3266bfc14c026.AAID': 957,
 '00019f447b3846e7a1c69c1ccc2a64d8.AAID': 958,
 '0001a66aed1e895899eaec1aa0c36688.AAID': 960,
 '0001aa6ebe5665127c1df51c036ac917.AAID': 1001,
 '0001accbd364413c42ba4ed7a4d3f10f.AAID': 1005,
 '0001b59e5733dddbe8fc96a0f0523288.AAID': 1011,
 '0001b831c40ac0e5b76a7ab54fa2f061.AAID': 1032,
 '0001bc23ada5e3f79a22612d94c023e2.IDFA': 1036,
 '0001c69cb95832401662a40c09c26e70.AAID': 1047,
 '0001ca3f36a2c6b3f3f2396ef9906ddf.AAID': 1064,
 '0001cb07909c0be73dadfc57ad54b328.AAID': 1181,
 '0001dd476e64d0247904febdee7c2c6c.IDFA': 1251,
 '0001dfa33f7e89161d492b12e1db35a4.AAID': 1252,
 '0001eb0af0eefb73daddf6e79fdc260b.AAID': 1257,
 '0001ebcd4e9c2bd958f0d9aba927fd2c.AAID': 1267,
 '0001f855f42b341007075d3b17636192.AAID': 1268,
 '0001fe13e2ca3e5fa365d8630e3a11ad.AAID': 1269,
 '0002059345975e01f538f944b1f3285d.AAID': 1283,
 '00020c77023a159d540c8fe0983561dc.AAID': 1289,
 '00021b1c5bd05aac3c529f6ab1d26ab8.AAID': 1355,
 '00021e8eae14000f2c26b4c5d77b79a4.AAID': 1356,
 '0002226a900567747f8c4ba2c47f8b66.AAID': 1362,
 '000225d68b8b99d2683a8ba25f21446f.AAID': 1374,
 '00022b49534245ca27d1179873b37900.AAID': 1375,
 '000240971c2eb61c9bc44f7b4a61c16c.AAID': 1389,
 '0002491483b2cf364c196cd047f15562.AAID': 1390,
 '0002527b6b732d47a495b31c357c1e61.AAID': 1404,
 '000267ab6baedc40a0de922b0d80b66b.AAID': 1405,
 '00029022909d97d05ae887b19be3d218.AAID': 1406,
 '0002a2827cefbd027b4338d77cb50f72.AAID': 1424,
 '0002ab5a429a536d8f4fa1678b4b8adb.AAID': 1425,
 '0002e4a560ed6419a65f881187971328.AAID': 1427,
 '0002fbf173b5ed294bb0db125ba2f322.AAID': 1593,
 '0002fc7753d31beb89039ee13d4893c5.AAID': 1594,
 '00030aff5a9132ef68bdf0f2b12c7eb6.AAID': 1595,
 '00031a9355cc79f4f865af3470ba6963.AAID': 1596,
 '00031c195d10646660acf8f86c9e5eac.AAID': 1598,
 '000328e33d5d5ce0e6a68a728a8f69da.IDFA': 1752,
 '0003330e5bb58c2cf4a927b075ef2cf9.AAID': 1778,
 '000333270fe855d6f6076a62d18f6c5e.AAID': 1779,
 '000333db095835105d676668b76efdad.AAID': 1815,
 '000335b2feb70e726f08e7ff9c1337f8.AAID': 1816,
 '00033d7709e86e74f4491b7883d7e43f.AAID': 1823,
 '00033ed397491a6fd6f00d1c26abd759.AAID': 1829,
 '000340ed10297297802d301cba1c45b0.AAID': 1837,
 '00034bb0298a87faf33a5b163bba42ad.AAID': 1848,
 '000363b6faed4d5f26742a6edf7d10c7.AAID': 1853,
 '0003693d7d106c83e5c451c1a667df25.IDFA': 1868,
 '000371dd5debe9eab7dfd6e3653614b1.AAID': 1869,
 '0003734b6421c51ffeec505279d5f5fe.AAID': 1870,
 '00037978f950f30ae22a003808ee8868.AAID': 1874,
 '00037ca8912b6d0eb0475b7f8b932b9b.AAID': 1899,
 '000388c397949da8d3d39263ce9f79ff.AAID': 2009,
 '00038f4e2aab629264fbfe440a3b3a7f.AAID': 2025,
 '0003a402ddf1ff3f869ae1637330f15c.AAID': 2032,
 '0003ac530ffa3ba42a5ac5aed15b3716.IDFA': 2035,
 '0003b8731c9540d7b8a8e05b0cd44589.IDFA': 2059,
 '0003c0811080d7d02bdbe4b150438039.AAID': 2062,
 '0003cd9fc573cf417a99fa5b8b02a6f1.AAID': 2063,
 '0003cf57e33ae1806f83995ca7568735.AAID': 2064,
 '0003d5f6f751be9479365aa8a12da189.IDFA': 2074,
 '0003d9f771a48d0fc1497db272d5c6fb.AAID': 2081,
 '0003dcffbffc00273df5fd65f4949362.AAID': 2084,
 '0003ec8768239a69acd96204d6b00a73.AAID': 2085,
 '0003f5393e0247fb7dccd82e87f0da76.AAID': 2086,
 '0003fb36df8f92e51d6776ae58cb2a79.AAID': 2088,
 '000416c7e2998a81ee7929fbc3d59484.AAID': 2091,
 '0004177980c9f7a7b1c0284261052843.AAID': 2095,
 '000423c350c19177a9c872708de19a6d.AAID': 2099,
 '00042bc69cb32733af1a90fd73df5e14.AAID': 2108,
 '00043dfd23f533038f4a74ea26284cdd.AAID': 2134,
 '0004412519d09183a467d9a6a34e4884.AAID': 2141,
 '0004438c2fcb0f0e0097faace5488602.AAID': 2145,
 '0004462f633dcde0fa2fd31138ae15bf.IDFA': 2167,
 '000450dfc9b043c7670b1428f59e1ed4.AAID': 2176,
 '00046418ced7960d1c82c1f63e8feb32.IDFA': 2177,
 '000469f3811e7e9bba83b5526422c656.AAID': 2198,
 '00046e040606e69002eea04e83b6ad07.IDFA': 2207,
 '00046f74293605b846eaf11570f28826.AAID': 2237,
 '00047294d1e4bd503b358b1de735c2e5.AAID': 2252,
 '000472a6353190bdde909e20c179ec1d.AAID': 2262,
 '0004756d594715dcfbf55faa93bcd200.IDFA': 2270,
 '000477a584479b280678e53de5151584.AAID': 2271,
 '00047941620a15971ed2852e0359f1a4.AAID': 2292,
 '00047cf9bfdab12e3b9e27c41f73f0ed.AAID': 2294,
 '00047e0ca8d6e69c75579e504f301f10.AAID': 2341,
 '000492be80904b3f243d3d75ebc17817.AAID': 2440,
 '0004936f5d5f9e889ab0a9b03e1b9c59.AAID': 2443,
 '00049979866831366e6a0868b565bdff.IDFA': 2449,
 '00049a147aa947d5b8b6d7d2d1f9dfa7.AAID': 2450,
 '00049a8ec4c4c7bffcd440324aba32cc.AAID': 2455,
 '00049ae58cac95ff4e2579d393603f37.AAID': 2456,
 '0004b570293de15a97b8f179c1f27270.AAID': 2471,
 '0004b5a343de928c2eebd374cc99a394.AAID': 2554,
 '0004b60b704faca2ff2db28046095f2f.AAID': 2568,
 '0004d09967f60805298d633d3d2c5081.AAID': 2569,
 '0004d0e7b671035f7f08296a7ac1cc9c.AAID': 2572,
 '0004d3373c9ce0b3d496b6d5c17f3303.AAID': 2576,
 '0004e371a0ab3008c974294f81b4cca3.AAID': 2584,
 '0004f4931073805cee01b074f3d83c74.IDFA': 2586,
 '0004fafc31603acf6bbc782dd9cc772a.AAID': 2592,
 '0004ff89736a0f050670de33216cd790.IDFA': 2593,
 '0005028ededb45040c190338992ad100.IDFA': 2643,
 '0005030fa4ff547ae8e9bc8b79119c99.AAID': 2648,
 '0005116f1f448b548f649c52870782b7.AAID': 2688,
 '0005155ace1ce64f967807edf43b393a.IDFA': 2692,
 '00051dfe2f5bb9af768860e2ab3240fb.AAID': 2713,
 '0005325ebe417af72524eaf6de1d4fab.AAID': 2767,
 '0005364cf5afb66539bad17dc89fef21.IDFA': 2770,
 '00053e761ac7a04392019113dbd81b25.AAID': 2788,
 '00055a7559fe47e760d93fa66226e9de.AAID': 2789,
 '000567b4b6fa4654c25697317ec7757a.AAID': 2790,
 '0005722774bbcfea9d9f1dbe073c8021.AAID': 2845,
 '00057cff06ef94096fc6d1623503256a.AAID': 2849,
 '0005830e04f56ea36c12449f4f36b0d5.AAID': 2938,
 '000584e0ec5f376df9ff49f83891e3d2.AAID': 2952,
 '00058bbdc71899fa526ddefb8cc87d6c.AAID': 2953,
 '0005afb9fa7b381ae9ed11c2373e0f3a.IDFA': 2967,
 '0005b53a959a812d62a4e50394657dd3.AAID': 2968,
 '0005b73803271bd035039b4d98474a97.AAID': 2969,
 '0005c1708e2e517a2db3243a6f3fb62b.AAID': 3003,
 '0005c30e55d56f8286ee0af989cfd52e.AAID': 3125,
 '0005c585a981a0fb6dae9ca020cc35b2.IDFA': 3126,
 '0005e50b995b57c62c7261592f682146.AAID': 3141,
 '0005e9486e291e8b72f4d39c49fbdc4d.AAID': 3145,
 '0005f94d1eee31cd7f10be891dee2a4d.AAID': 3148,
 '000630bac24c530ab08651c7e7eaaff0.AAID': 3150,
 '000633e35a10596a516f6c168187aeaa.AAID': 3153,
 '0006444fc8ad3509358b4efbd25d37f3.AAID': 3156,
 '000649ad7313019a30f8c8c78dd7b310.AAID': 3157,
 '00064bc7e05b9262b66b503a8ff24e22.AAID': 3170,
 '00064dc0c83f3b615cca12fcfcc82384.AAID': 3173,
 '000655881d5e2cc2a6d5c3a95387a29c.AAID': 3180,
 '00065b290aeabb1eb44d298146f957e7.AAID': 3202,
 '00066d3aed63e3c4a8bf390a897e4c9d.AAID': 3319,
 '00066d5b21a457876301cd350d0fc4e4.AAID': 3324,
 '000676b45bd23a313da32db0466505dd.AAID': 3328,
 '000699aeafc5c1bc4eb5afe95fba8264.IDFA': 3360,
 '00069b7af75a91c76967fac94da05bb9.AAID': 3405,
 '00069cbd4fcca42393e0c5db40c61193.AAID': 3407,
 '0006b03bc103913a2cd5371bf7fb26e0.AAID': 3433,
 '0006bc61e891ee7298c6dc476e894036.IDFA': 3458,
 '0006c07173b668f338cbab3218957e29.AAID': 3462,
 '0006c1fe36bc1fc99ca8f680e88032bd.AAID': 3466,
 '0006c43bfb38c4514197cb712176cd90.IDFA': 3469,
 '0006d1f45c5170c1040f87f27a18ec8d.AAID': 3470,
 '0006d69347e66e612510dd3dd5de6752.IDFA': 3620,
 '0006d73d3591c5150b866b7fa8a18fb4.AAID': 3624,
 '0006db10e6997ef76061ad0870146c5e.AAID': 3652,
 '0006de8d294677403ff7ca01b13a0fff.AAID': 3663,
 '0006e0dc2de05ed2e8845fef406ee0b1.AAID': 3803,
 '0006e63812923c4af1be4e367073eb37.AAID': 3810,
 '00070512f5733fd9cf5797c419735354.AAID': 3811,
 '00070c2582dceb3f51779a0620162f3e.AAID': 3831,
 '00070e111288de0686c5845c748e3954.AAID': 3833,
 '00070f602a2b0ab70fd08dbb000fcbd6.AAID': 3834,
 '0007155a77c25193e4949858c821dc27.IDFA': 3851,
 '0007346a74a685fb8efd9be5f1dea9ef.IDFA': 3854,
 '00073586a7af8171b24d24db5f9f5d93.AAID': 3880,
 '000740476d093d1930253b4dc61c1541.AAID': 3886,
 '00074389de6a2fa08a3d8fa5ffb724d4.AAID': 3892,
 '0007486a38007d7cf27d4cf02125038d.AAID': 3893,
 '000748e1536730667375bfafb6897a80.IDFA': 3898,
 '000757a786ac96cd31c55c3f2db9a2d2.AAID': 3907,
 '00075b6c96d8f1b41b18677e84d92906.AAID': 3910,
 '000765aaaf862b57078ccab94d122a3d.AAID': 3911,
 '000775f8d521b1af96e4f05a87916407.AAID': 3915,
 '00077afe6531de4b54511fb36d84d2e1.AAID': 3926,
 '0007834925bffc24afa3a7bfec8fbe64.AAID': 3953,
 '00078904fdd18f56d93abf8d4c3b89e6.AAID': 3995,
 '00078b6c1e63227048fbd3b43023b837.AAID': 4004,
 '0007958669b5f62a9d56d58749ed3781.AAID': 4005,
 '000796618f320551b20b83ffb69c6d36.AAID': 4009,
 '0007a02d921000a975a2d3edaf2079d4.AAID': 4077,
 '0007a92af7e5f5e1398b7a6b5685d1d4.AAID': 4079,
 '0007b13e8f5eb920c6f40b24bd7856ab.AAID': 4082,
 '0007c95298c161802452a51fd2a7778f.IDFA': 4083,
 '0007d3f8f28daf80f40708bdbfddf2f8.AAID': 4084,
 '0007ddedc44f04b41e30bea7a8a5ec3c.AAID': 4104,
 '0007e0ef406d912555cc18dab7d61231.AAID': 4105,
 '0007eeac107786d32337c13aedb55a75.AAID': 4236,
 '0007f25e0dd53af64355989b07038387.AAID': 4252,
 '0007f9a5f7a4756c90934348530a6113.AAID': 4253,
 '00080989d696f9b43029586ba1974990.AAID': 4254,
 '000813cb4a86360d5f3cb3e3f5db2175.AAID': 4259,
 '000821371cc5f3e6f410b528acc0e869.AAID': 4287,
 '0008276c979e01e73ef7f48f9d9b545d.AAID': 4288,
 '00082afa048be4caafeae0cb6f5717ed.AAID': 4297,
 '0008305159cb518d767155fc0d1f10c7.AAID': 4313,
 '0008451f79690e6df2ea279697df5c41.AAID': 4319,
 '000852c1921d9fb6f0db32864faef31f.AAID': 4320,
 '00085a61e94d9d72407c083a43a7d0f1.AAID': 4328,
 '00086104000447f6d5aeb58c6eb760ae.AAID': 4330,
 '0008709f3866f41d536fe488c2431897.AAID': 4331,
 '000872c1d06a2c8b23d24ad54ceaf521.AAID': 4332,
 '00087a2c304d760bf2e01f1ed4d3e668.AAID': 4333,
 '00087e00053f831de58ca599c176cba5.AAID': 4334,
 '00089274109d2ea07343dd042454c5e4.AAID': 4382,
 '0008974972fab84d1539eae77b58bf0e.AAID': 4387,
 '00089a8b73cb957ce260439d9f77cac4.AAID': 4391,
 '0008cd244779a02a6d6cef489afdc058.AAID': 4432,
 '0008da491462627faeca5ef89592097d.AAID': 4455,
 '0008e284c0c24f1fbb4f79f11cfc5523.AAID': 4457,
 '0008e2f57eafa9a11ab6977f74fba752.AAID': 4471,
 '0008e5831b90c3cb6c59bc96edc114f0.IDFA': 4557,
 '0008e62928469ac77141184452092c6d.AAID': 4558,
 '0008ecf3d2da40111e11d69f08a2d0d9.AAID': 4634,
 '0008f47d08b7eaef47cf7a8d917398fa.IDFA': 4708,
 '0008fa6e517f217604bc04eca229fbab.AAID': 4709,
 '0008feda96e99dfc4a3f5b946520f921.IDFA': 4770,
 '000914a113cff537756b3ff6033c52c0.AAID': 4776,
 '00091b78f04a700b3fb91c91177150aa.AAID': 4914,
 '000934e8587b96e1ccd1c93c182700a9.AAID': 4940,
 '0009449807f0bfa8ea0147e42eb5153e.AAID': 4943,
 '00095ab8b67ea6935dce83f9f3da89f1.AAID': 4947,
 '00095c63ab6eb2c1e93b39b2e8ba2c0a.AAID': 4964,
 '00095d167b7df98e25d7e5f3dedcc097.AAID': 4965,
 '0009614e2239d83c9936696d3c987501.AAID': 5021,
 '000961f87444ed68d776c422b12f0b90.AAID': 5056,
 '0009705c7c2eb73a8c7f6995e540fcf8.AAID': 5057,
 '000971808e46e8873e19170a657b09a2.AAID': 5059,
 '000974a8cfa7ea5503a97285b466f91a.AAID': 5064,
 '00097f2c874bb19cf3bd927bf13fb2a2.IDFA': 5065,
 '0009850c8c46d51ac6e71b57f7802603.AAID': 5093,
 '00098e006dfe7e81f7886fcff55c0c11.AAID': 5094,
 '000991b17f41bd0a58f214feec1d0bd2.IDFA': 5104,
 '00099e9ad3eeea51e5e2ad4a6f0ebc40.AAID': 5121,
 '0009a0ebfee57c560c1b1a60e2988fa2.AAID': 5122,
 '0009a4e848462e60d3af73e11b0c4b54.IDFA': 5123,
 '0009a648cab8108c8d30dde6a29002d2.AAID': 5163,
 '0009b08db0ee66771dfe60a8fb7e6b31.AAID': 5164,
 '0009b430a554b445cfeaa7bb1408ff16.AAID': 5232,
 '0009bb462e52ef05811dca313b91314e.AAID': 5239,
 '0009bb5d695ee589a2d78d2bc6d33594.AAID': 5253,
 '0009c18b34171b2bbb3045092b72fd02.AAID': 5254,
 '0009c8bae70e051eee00687c910a1a67.IDFA': 5458,
 '0009ec43e5827ad3d74807e632ad9170.AAID': 5460,
 '0009ef4a99ff2b24aec6cb4da37ad685.AAID': 5463,
 '0009f4f2d5a9d7febfc34102a311f4f9.AAID': 5481,
 '000a113fa53eec99fa2ad433c586eddd.IDFA': 5507,
 '000a1579032bd2f320058f33375d8dfa.AAID': 5546,
 '000a15ecf229ed48169b1cf48c204051.AAID': 5568,
 '000a1864fe66fb534fa0d2d3d198fe35.AAID': 5573,
 '000a47276444bbbb57c34d9964f87057.AAID': 5583,
 '000a491a22f2a7878b671839fead92dd.AAID': 5591,
 '000a49fe31115171608f782892c2d272.AAID': 5598,
 '000a4a43e9beaece5840c80745bf2227.AAID': 5617,
 '000a4ee0d3faeafbea99cc9f76d9fe68.AAID': 5623,
 '000a4fcd806785ba6ee864bef73c1f36.AAID': 5644,
 '000a506dc9f76c8381d9792bd50dd923.IDFA': 5645,
 '000a5d7be9ad26502a6f987ec4dffee4.AAID': 5649,
 '000a65d1145533f5e6854fff221a98b6.AAID': 5662,
 '000a7c2652982b11dacf634aaeab711f.AAID': 5664,
 '000a86c28555b3e3e880747002049b55.AAID': 5665,
 '000a87f8905f0e8038cb89f0b7b3e148.AAID': 5674,
 '000a9f752aa95a706ee8bb7f0670807b.AAID': 5677,
 '000aa1d6aa3ff0124d805d68ab859948.AAID': 5678,
 '000aa2af121a6b03606f0f76e005d029.AAID': 5679,
 '000aaf696ae32f5a41a39c01e67c4842.IDFA': 5680,
 '000ab2a898f3d7a6e5c6d827f66f41fc.AAID': 5684,
 '000ac40f269be9451458cc1f9384feea.AAID': 5747,
 '000ac92ebf8d3c0821fd432311318f05.AAID': 5769,
 '000acd199683d2457607c7751426edbb.AAID': 5777,
 '000aebe66cd845fdc22ee18d34751124.AAID': 5783,
 '000aeda6e1f77df517b4d7168a0443fc.AAID': 5784,
 '000af7a4d83733068400c4ad1bed4166.AAID': 5797,
 '000aff0286a1d603a5009edb6155679e.AAID': 5799,
 '000b033e03434b3406422bfbc2f40bcf.IDFA': 5800,
 '000b07f1a60ca0127dc07d991ed5e05d.AAID': 5801,
 '000b0f9e8a3d90618ec272b5538efffa.AAID': 5804,
 '000b12cf1271ae888554c78ea0e6b7a7.AAID': 5807,
 '000b20048128a4b118d541035826f7bf.AAID': 5819,
 '000b272db5d9722a4dad936f2fca87af.AAID': 5895,
 '000b2baffc2ab4071294b0e33569a517.AAID': 5898,
 '000b32c2ab608be2db5f75e8caf8fef4.AAID': 5899,
 '000b336e095ae31fabad9dbcde670e18.IDFA': 5900,
 '000b5d36f1961379dfef28a44eb52658.IDFA': 5901,
 '000b60a4ba84bd5ae563a32268d01356.AAID': 5902,
 '000b678d13d3a609044f583463742138.IDFA': 5903,
 '000b67dee3832cdf5bff809be393d71f.AAID': 5904,
 '000b6a03235e0c336d71d390ac3cf85c.IDFA': 5931,
 '000b6cf1328c45f91fe395d853cb93c7.AAID': 5950,
 '000b7cc3be4293a59d484bd159bee91f.AAID': 5959,
 '000b81dc510852939cfddb7e5f169262.AAID': 5961,
 '000b8e7719645a78909a3214aa8e0270.AAID': 5963,
 '000bb5dddc73797155854a1b37c5a394.AAID': 5976,
 '000bb8f051814d48c278ce215acfcf79.AAID': 5987,
 '000bea178ea1208fc155b6c8ab4d7f8e.AAID': 5991,
 '000befc6217f344b30cb729f21cd0994.AAID': 5996,
 '000bfb638bc9a8da524e0c295f7cc366.AAID': 6001,
 '000c0156837060ae0bfac5348d158f7b.IDFA': 6002,
 '000c08d53099598c10728bbf97516c46.AAID': 6007,
 '000c0c479a4566054585e8443f200bc6.AAID': 6012,
 '000c137ecbe792f916e457e95370025c.AAID': 6017,
 '000c1e90a9402d85f921c1f9d783ce0d.AAID': 6024,
 '000c24932bfb1b9d5fd8236b1a4bf89e.AAID': 6039,
 '000c2f466f621e84106208be34e63e4c.AAID': 6094,
 '000c3508d481e4726e1c56ccc7d77590.AAID': 6170,
 '000c392f962cb5da8ded9816c4e624dc.AAID': 6172,
 '000c3a24dbc53fbe3c0127e581a18bd7.AAID': 6175,
 '000c3c75013be7bcd656f877fecba863.AAID': 6306,
 '000c3f6fc6cdab9d8707eab0c84fdaf5.AAID': 6343,
 '000c4e5eb9e29407b7e6798ba0aa0f57.AAID': 6358,
 '000c4ef5d19dbd25cac6dd6b0f4c58b8.AAID': 6359,
 '000c535203a6e7905cfd96b2776e4794.AAID': 6360,
 '000c5618b5ec5789b383201a69828f8c.AAID': 6381,
 '000c61605d746fd91ee159075a7497cf.AAID': 6459,
 '000c63b6efa2f8e6eaac1f72be896ae1.AAID': 6476,
 '000c6d1416a59df388edc0a10b96b570.IDFA': 6492,
 '000c7bbb373a3a377e662db8bc89813d.AAID': 6494,
 '000c89da6f8b7d034d6c07d95ede9ad0.AAID': 6495,
 '000c9e37b797a96f7e43ef69be67e9cf.AAID': 6584,
 '000c9f62f474ec263ddeebc70f4c6712.AAID': 6585,
 '000ca64b97a0530f46341d55ccc9f3c1.AAID': 6594,
 '000cb59af06207e123f692dad07ee6dd.AAID': 6596,
 '000cba9d4811c588cbbde5d987083bb3.IDFA': 6597,
 '000ccab457317efd75a6d461625a0b00.AAID': 6638,
 '000ccef31f98643c88dfbacfb69c76d5.AAID': 6647,
 '000ccff62ac765c4b6f6f93e064efa7a.AAID': 6654,
 '000cd7df41719d6c7502c52fc0b1a167.IDFA': 6657,
 '000cef942cb498da0ee7bc6c20f2f765.AAID': 6689,
 '000cf6c102da77c5b102f9b95e513fa2.AAID': 6690,
 '000d18613fb0d25b84f10d12878f4282.IDFA': 6706,
 '000d1c85ac6c4e4c49d8bfda9d766696.AAID': 6716,
 '000d29fd91c3f4c9b29a119f2c6dfd61.AAID': 6719,
 '000d43c998ca8c940e4cc8a373ec21f2.AAID': 6724,
 '000d57f1c8005e2218a3db37ff5372f4.AAID': 6729,
 '000d59e2d68049731054a63e3d9811ed.AAID': 6797,
 '000d6f2ba7adbb9d0e939fd71f99c126.AAID': 6798,
 '000d77364188f1911557bde13d46fea9.AAID': 6807,
 '000d8143e8824f5096c58eee05b10fb2.AAID': 6808,
 '000d8642679f979c4653d8390a2543e0.AAID': 6812,
 '000d8b770a056f410d02e433ba95ee9d.AAID': 6814,
 '000d8bbb8dbce44f30fa29941b1318dc.IDFA': 6821,
 '000d9027262947d7a349efd4949d7c8b.AAID': 6891,
 '000da56a3e5b9261d8643e7e9f6636e6.AAID': 6912,
 '000da742fbc32c99da9e480173a9a43a.AAID': 6913,
 '000dbac9f257d2c4c961ef29d2d66109.AAID': 6942,
 '000dbd7d340d62229f6cdd7cd7e3b06a.IDFA': 6958,
 '000dbe3daf191fb08b283f0eed32f4b3.AAID': 6979,
 '000dc1d388e45aa44a456a3a0e14c614.AAID': 6990,
 '000dc6d72782deb9d0fd632f606ef28c.IDFA': 6994,
 '000dc77234d4e7ce21eb262eda885311.AAID': 7001,
 '000de179e28d4a3cae009c932b79baee.AAID': 7002,
 '000de27983559db4638b7b10b83e8adc.AAID': 7006,
 '000df3150804210e8e9744e95a2cad08.AAID': 7007,
 '000df6d979ef469be38e39da1b79b7d1.AAID': 7008,
 '000e14a3eddc352898b68881d8adbc88.AAID': 7041,
 '000e21b1b96256e12c5235a35450385e.AAID': 7044,
 '000e25539d210b56798bcd1491894f34.AAID': 7045,
 '000e2f1cb72ecc982e1fe172f84badce.AAID': 7046,
 '000e35537ec281bd04a91c9410bdb4af.AAID': 7048,
 '000e409e9ee3a72ecb2906ba6582a5bb.AAID': 7049,
 '000e43976a9b8751bcac2505ef0f7489.AAID': 7083,
 '000e443e359982f911592300711d1ec8.AAID': 7236,
 '000e4c78ed6a31f942795f957119806b.AAID': 7312,
 '000e585752ee97a4e800794003b74b4e.AAID': 7451,
 '000e5c7412b3db998fce445cd2d9e065.IDFA': 7507,
 '000e5d91db0a625d3230df78db20e496.AAID': 7520,
 '000e5ff9e678ab34714f0b4c839baea0.AAID': 7521,
 '000e798ee078ad7e882449b90f551422.AAID': 7546,
 '000e7be97d998c393415f1cba07d9bdf.IDFA': 7548,
 '000e85730ffbf67383caf2b2b52cefb4.IDFA': 7561,
 '000e8c8dd87b134b458a51fcedf67b44.AAID': 7565,
 '000e95b4a15d65f98d30dba014e0c64f.AAID': 7566,
 '000e9724679d9a3d3b5362991e2d3107.AAID': 7572,
 '000e9b0ab773b7d35524a629e680edb1.AAID': 7573,
 '000ea2714889f8625ecd90a6aea6df8d.AAID': 7574,
 '000eae9a3b78e41db614c27a67f62beb.AAID': 7660,
 '000eb18022d9028057d1a2c92f12c205.AAID': 7669,
 '000edaf5358c12171e75522cb2f45c12.AAID': 7670,
 '000edd2ffa4a3c6a9f48a5571a80060f.AAID': 7676,
 '000ee0735429f707c71f65b0d4314bd3.AAID': 7765,
 '000eeb91355064c387728d689ed6f4d4.IDFA': 7766,
 '000ef464e6958c46e72ce6c44e12301e.AAID': 7767,
 '000ef4ff97ee93ccef491e2ca8bf55ac.AAID': 7774,

## create partitions from original IDs

In [4]:
partition = create_partitions(lookup)

with open(f"{OUTPUT}/partition.json", "w") as fp:
    json.dump(partition, fp, indent=1)

### descriptives

In [12]:
partition_distribution = (
    pd.DataFrame({"partition": partition.values(), "device_id": partition.keys()})
    .groupby("partition")["device_id"]
    .count()
    .reset_index()
)
partition_distribution["device_id"].describe()

count     256.000000
mean     6455.867188
std       114.608857
min      6154.000000
25%      6383.750000
50%      6459.500000
75%      6537.250000
max      6766.000000
Name: device_id, dtype: float64