In [1]:
import math
from datetime import timedelta

import polars as pl
import polars_distance as pld
import polars_h3 as plh3
import yaml
from haversine import haversine

# https://ion-elgreco.github.io/polars-distance/api/dist/#polars_distance.DistancePairWise.haversine

with open("../config.budapest.yaml") as fp:
    config = yaml.safe_load(fp)

In [33]:
def rg(data: pl.DataFrame) -> pl.DataFrame:
    d = data.with_columns(
        pl.struct("longitude_mean", "latitude_mean")
        .alias("stop")
        .struct.rename_fields(["longitude", "latitude"]),
        pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean())
        .alias("centroid")
        .struct.rename_fields(["longitude", "latitude"]),
    ).with_columns(
        pld.col("centroid").dist.haversine("stop", "km").alias("haversine"),
        pl.col.interval_lenght.dt.total_seconds().sum().alias("N"),
    )
    res = (
        ((d["haversine"] ** 2 * d["interval_lenght"].dt.total_seconds()).sum() / d["N"])
        .sqrt()
        .round(3)[0]
    )
    return pl.DataFrame({"device_id": [data["device_id"][0]], "result": [res]})


def rg_place(data: pl.DataFrame) -> pl.DataFrame:
    d = data.with_columns(
        pl.struct("longitude_mean", "latitude_mean")
        .alias("stop")
        .struct.rename_fields(["longitude", "latitude"]),
        pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean())
        .alias("centroid")
        .struct.rename_fields(["longitude", "latitude"]),
    ).with_columns(
        pld.col("centroid").dist.haversine("stop", "km").alias("haversine"),
    )
    place_counts = d.group_by("place_label").len()
    N = place_counts["len"].sum()
    d = d.join(place_counts, on="place_label", how="inner").unique(
        subset=("place_label")
    )
    res = round(math.sqrt((d["haversine"] ** 2 * d["len"]).sum() / N), 3)
    return pl.DataFrame({"device_id": [data["device_id"][0]], "result": [res]})

In [4]:
DIR = f"{config['dirs']['output']}/{config['city']}"

In [5]:
for i in range(1):
    temp = pl.read_parquet(f"{DIR}/stops/v2/{i:02x}.parquet")

In [7]:
test = pl.DataFrame(
    {
        "device_id": [1, 1, 1, 1, 1],
        "place_label": [1, 1, 2, 2, 2],
        "interval_lenght": [
            timedelta(minutes=20),
            timedelta(minutes=30),
            timedelta(minutes=25),
            timedelta(minutes=15),
            timedelta(minutes=10),
        ],
        "latitude_mean": [
            47.6612,
            47.6612,
            47.4984,
            47.4984,
            47.4984,
        ],
        "longitude_mean": [19.0764, 19.0764, 19.0404, 19.0404, 19.0404],
    }
)

In [8]:
c_lat = test["latitude_mean"].mean()
c_lon = test["longitude_mean"].mean()
p1 = haversine((c_lat, c_lon), (47.6612, 19.0764))
p2 = haversine((c_lat, c_lon), (47.4984, 19.0404))

In [9]:
round(
    math.sqrt(
        sum([i**2 * n for i, n in zip([p1, p1, p2, p2, p2], [20, 30, 25, 15, 10])])
        / 100
    ),
    3,
)

9.333

In [10]:
round(math.sqrt(sum([i**2 * n for i, n in zip([p1, p2], [2, 3])]) / 5), 3)

8.967

In [12]:
test.group_by("device_id").map_groups(rg)
test.group_by("device_id").map_groups(rg_place)

shape: (1, 2)
┌───────────┬────────┐
│ device_id ┆ result │
│ ---       ┆ ---    │
│ i64       ┆ f64    │
╞═══════════╪════════╡
│ 1         ┆ 8.967  │
└───────────┴────────┘

In [13]:
for _ in range(1000):
    test.group_by("device_id").map_groups(rg)

In [31]:
def rg_plh3(data: pl.DataFrame) -> pl.DataFrame:
    d = data.with_columns(
        pl.col.latitude_mean.mean().alias("c_lat"),
        pl.col.longitude_mean.mean().alias("c_lon"),
    ).with_columns(
        plh3.great_circle_distance(
            "latitude_mean",
            "longitude_mean",
            "c_lat",
            "c_lon",
            unit="km",
        ).alias("haversine"),
        pl.col.interval_lenght.dt.total_seconds().sum().alias("N"),
    )
    res = (
        ((d["haversine"] ** 2 * d["interval_lenght"].dt.total_seconds()).sum() / d["N"])
        .sqrt()
        .round(3)[0]
    )
    return pl.DataFrame({"device_id": [data["device_id"][0]], "result": [res]})


def rg_hexagon(data: pl.DataFrame, res: int) -> pl.DataFrame:
    c_lat = data["latitude_mean"].mean()
    c_lon = data["longitude_mean"].mean()
    d = data.with_columns(
        plh3.latlng_to_cell(c_lat, c_lon, resolution=res).alias("center"),
        plh3.int_to_str(
            plh3.latlng_to_cell(pl.col("latitude_mean"), pl.col("longitude_mean"), res)
        ).alias(f"h3_{res}"),
    ).with_columns(
        plh3.grid_distance("center", f"h3_{res}").alias("distance"),
        pl.col(f"h3_{res}").count().alias("N"),
    )
    place_counts = d.group_by(f"h3_{res}").len()
    N = place_counts["len"].sum()
    d = d.join(place_counts, on=f"h3_{res}", how="inner").unique(subset=(f"h3_{res}"))
    res = round(math.sqrt((d["distance"] ** 2 * d["len"]).sum() / N), 3)
    return pl.DataFrame({"device_id": [data["device_id"][0]], "result": [res]})

In [16]:
rg_plh3(test)

shape: (1, 6)
┌───────────┬─────────────┬─────────────────┬───────────────┬────────────────┬────────┐
│ device_id ┆ place_label ┆ interval_lenght ┆ latitude_mean ┆ longitude_mean ┆ result │
│ ---       ┆ ---         ┆ ---             ┆ ---           ┆ ---            ┆ ---    │
│ i64       ┆ i64         ┆ duration[μs]    ┆ f64           ┆ f64            ┆ f64    │
╞═══════════╪═════════════╪═════════════════╪═══════════════╪════════════════╪════════╡
│ 1         ┆ 1           ┆ 20m             ┆ 47.6612       ┆ 19.0764        ┆ 9.336  │
└───────────┴─────────────┴─────────────────┴───────────────┴────────────────┴────────┘

In [29]:
rg_hexagon(test, 8)

shape: (1, 2)
┌───────────┬────────┐
│ device_id ┆ result │
│ ---       ┆ ---    │
│ i64       ┆ f64    │
╞═══════════╪════════╡
│ 1         ┆ 11.764 │
└───────────┴────────┘

In [32]:
temp.group_by("device_id").map_groups(rg_plh3)

shape: (4_697, 2)
┌───────────┬────────┐
│ device_id ┆ result │
│ ---       ┆ ---    │
│ i64       ┆ f64    │
╞═══════════╪════════╡
│ 1578      ┆ 5.447  │
│ 3162      ┆ 1.128  │
│ 5648      ┆ 16.823 │
│ 4850      ┆ 0.028  │
│ 926       ┆ 2.355  │
│ …         ┆ …      │
│ 506       ┆ 6.465  │
│ 4046      ┆ 0.005  │
│ 899       ┆ 0.0    │
│ 381       ┆ 7.177  │
│ 5889      ┆ 0.0    │
└───────────┴────────┘

In [81]:
temp.group_by("device_id").map_groups(rg)

shape: (4_696, 16)
┌─────────────┬─────────┬─────────────┬─────────────┬───┬────────────┬───────────┬────────┬────────┐
│ device_id   ┆ stop_id ┆ interval_st ┆ interval_st ┆ … ┆ centroid   ┆ haversine ┆ N      ┆ result │
│ ---         ┆ ---     ┆ art         ┆ op          ┆   ┆ ---        ┆ ---       ┆ ---    ┆ ---    │
│ str         ┆ i32     ┆ ---         ┆ ---         ┆   ┆ struct[2]  ┆ f64       ┆ i64    ┆ f64    │
│             ┆         ┆ datetime[μs ┆ datetime[μs ┆   ┆            ┆           ┆        ┆        │
│             ┆         ┆ , Europe/Bu ┆ , Europe/Bu ┆   ┆            ┆           ┆        ┆        │
│             ┆         ┆ dapest]     ┆ dapest]     ┆   ┆            ┆           ┆        ┆        │
╞═════════════╪═════════╪═════════════╪═════════════╪═══╪════════════╪═══════════╪════════╪════════╡
│ 00f70fce9f3 ┆ 1       ┆ 2023-10-27  ┆ 2023-10-27  ┆ … ┆ {19.190824 ┆ 2.647667  ┆ 146016 ┆ 14.244 │
│ bb2942e9238 ┆         ┆ 02:15:10    ┆ 02:22:04    ┆   ┆ ,47.527842 ┆           ┆        ┆        │
│ dfd9960b…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 0093107f977 ┆ 1       ┆ 2024-10-05  ┆ 2024-10-05  ┆ … ┆ {18.830269 ┆ 0.397394  ┆ 2130   ┆ 0.514  │
│ 19ed33f6e48 ┆         ┆ 02:35:08    ┆ 02:53:35    ┆   ┆ ,47.438448 ┆           ┆        ┆        │
│ e030b01d…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 009694d5bba ┆ 1       ┆ 2025-12-23  ┆ 2025-12-23  ┆ … ┆ {19.9749,4 ┆ 0.0       ┆ 440    ┆ 0.0    │
│ cb1ecb734bb ┆         ┆ 16:09:02    ┆ 16:16:22    ┆   ┆ 8.034006}  ┆           ┆        ┆        │
│ 62a9c854…   ┆         ┆ CET         ┆ CET         ┆   ┆            ┆           ┆        ┆        │
│ 004c98e5a49 ┆ 1       ┆ 2025-08-28  ┆ 2025-08-28  ┆ … ┆ {19.092882 ┆ 2.48538   ┆ 76444  ┆ 2.132  │
│ ac8a2d7e251 ┆         ┆ 15:19:15    ┆ 15:30:32    ┆   ┆ ,47.507695 ┆           ┆        ┆        │
│ 5e51373c…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 00b8434096b ┆ 1       ┆ 2023-12-13  ┆ 2023-12-13  ┆ … ┆ {19.128227 ┆ 12.157867 ┆ 629884 ┆ 7.974  │
│ fdc9ec58857 ┆         ┆ 09:42:55    ┆ 09:52:14    ┆   ┆ ,47.550818 ┆           ┆        ┆        │
│ a147bb7b…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
│ …           ┆ …       ┆ …           ┆ …           ┆ … ┆ …          ┆ …         ┆ …      ┆ …      │
│ 00599b7d2ee ┆ 1       ┆ 2025-06-22  ┆ 2025-06-22  ┆ … ┆ {19.111834 ┆ 7.793884  ┆ 2195   ┆ 5.67   │
│ 8d06336ca49 ┆         ┆ 20:20:57    ┆ 20:34:34    ┆   ┆ ,47.49461} ┆           ┆        ┆        │
│ c98ca5e4…   ┆         ┆ CEST        ┆ CEST        ┆   ┆            ┆           ┆        ┆        │
│ 00e88bd3e0f ┆ 1       ┆ 2023-11-05  ┆ 2023-11-05  ┆ … ┆ {18.844284 ┆ 21.345006 ┆ 3951   ┆ 18.971 │
│ cd94d5e4aa5 ┆         ┆ 09:44:29    ┆ 09:50:38    ┆   ┆ ,47.367169 ┆           ┆        ┆        │
│ aeb046b3…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
│ 001db4a1248 ┆ 1       ┆ 2025-07-15  ┆ 2025-07-15  ┆ … ┆ {19.121671 ┆ 8.620419  ┆ 871653 ┆ 4.303  │
│ ca9db6d1cf5 ┆         ┆ 09:18:09    ┆ 10:09:34    ┆   ┆ ,47.510319 ┆           ┆        ┆        │
│ 38f0fca2…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 002564c6cc0 ┆ 1       ┆ 2025-05-04  ┆ 2025-05-04  ┆ … ┆ {19.176849 ┆ 12.24473  ┆ 715191 ┆ 13.304 │
│ 82f3b0c0c48 ┆         ┆ 10:32:19    ┆ 10:42:42    ┆   ┆ ,47.432964 ┆           ┆        ┆        │
│ 5dd70bfa…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 004416a7490 ┆ 1       ┆ 2023-12-13  ┆ 2023-12-13  ┆ … ┆ {19.101195 ┆ 2.428283  ┆ 48798  ┆ 5.447  │
│ 583d7ec56cd ┆         ┆ 02:12:26    ┆ 04:49:40    ┆   ┆ ,47.436017 ┆           ┆        ┆        │
│ 1ee93813…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
└─────────────┴─────────┴─────────────┴─────────────┴───┴────────────┴───────────┴────────┴────────┘