In [1]:
import polars as pl
import yaml

with open("../config.budapest.yaml") as fp:
    config = yaml.safe_load(fp)

In [2]:
DIR = f"{config['dirs']['output']}/{config['city']}_ids_not_replaced"

In [3]:
for i in range(1):
    temp = pl.read_parquet(f"{DIR}/stops/v2/{i:02x}.parquet")

In [5]:
temp

shape: (548_130, 11)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id  ┆ stop_id ┆ interval_ ┆ interval_ ┆ … ┆ latitude_ ┆ longitude ┆ number_of ┆ place_lab │
│ ---        ┆ ---     ┆ start     ┆ stop      ┆   ┆ std       ┆ _std      ┆ _pings    ┆ el        │
│ str        ┆ i32     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ datetime[ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ u32       ┆ i64       │
│            ┆         ┆ μs, Europ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ e/Budapes ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ t]        ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 0.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 07:24:06  ┆ 07:35:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 2       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 1.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:23:47  ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 3       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:50:40  ┆ 10:58:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 4       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 12:41:20  ┆ 12:49:26  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 5       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 4         ┆ 12        │
│ 6276495c5a ┆         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 11:06:43  ┆ 11:22:57  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00ffd69f07 ┆ 381     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 14.0      ┆ 12.0      ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 18:27:21  ┆ 18:37:33  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 382     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 11.0      ┆ 6.0       ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 21:11:36  ┆ 21:26:20  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 383     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 9.0       ┆ 2.0       ┆ 4         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 04:47:22  ┆ 05:13:19  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 384     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 5.0       ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 08:04:50  ┆ 08:27:17  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 385     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 13.0      ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 09:08:14  ┆ 09:43:51  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
import polars_distance as pld
# https://ion-elgreco.github.io/polars-distance/api/dist/#polars_distance.DistancePairWise.haversine

In [ ]:
data.select(
    pld.col("longitude_mean").dist.haversine("latitude_mean", "km").alias("haversine")
)

In [ ]:
data = temp.filter(pl.col.device_id.str.starts_with("0000051fc26276495c5a9ab1753a70"))[
    :3
].clone()

In [72]:
def rg(data: pl.DataFrame) -> pl.DataFrame:
    d = data.with_columns(
        pl.struct("longitude_mean", "latitude_mean")
        .alias("stop")
        .struct.rename_fields(["longitude", "latitude"]),
        pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean())
        .alias("centroid")
        .struct.rename_fields(["longitude", "latitude"]),
    ).with_columns(
        pld.col("centroid").dist.haversine("stop", "km").alias("haversine"),
        pl.col.interval_lenght.dt.total_seconds().sum().alias("N"),
    )
    res = (
        ((d["haversine"] ** 2 * d["interval_lenght"].dt.total_seconds()).sum() / d["N"])
        .sqrt()
        .round(3)[0]
    )
    return data.head(1).with_columns(pl.lit(res).alias("result"))

In [58]:
q = rg(data)
q

8.241283721822473

In [50]:
((q["haversine"] ** 2 * q["interval_lenght"].dt.total_seconds()).sum() / q["N"]).sqrt()

shape: (3,)
Series: 'N' [f64]
[
	8.241284
	8.241284
	8.241284
]

In [74]:
temp.group_by("device_id").map_groups(rg)

shape: (4_696, 12)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬────────┐
│ device_id  ┆ stop_id ┆ interval_s ┆ interval_s ┆ … ┆ longitude_ ┆ number_of ┆ place_lab ┆ result │
│ ---        ┆ ---     ┆ tart       ┆ top        ┆   ┆ std        ┆ _pings    ┆ el        ┆ ---    │
│ str        ┆ i32     ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ f64    │
│            ┆         ┆ datetime[μ ┆ datetime[μ ┆   ┆ f64        ┆ u32       ┆ i64       ┆        │
│            ┆         ┆ s, Europe/ ┆ s, Europe/ ┆   ┆            ┆           ┆           ┆        │
│            ┆         ┆ Budapest]  ┆ Budapest]  ┆   ┆            ┆           ┆           ┆        │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪════════╡
│ 00f99a3c6c ┆ 1       ┆ 2024-12-08 ┆ 2024-12-08 ┆ … ┆ 3.0        ┆ 6         ┆ 1         ┆ 5.311  │
│ d32fff46b7 ┆         ┆ 17:56:03   ┆ 18:01:17   ┆   ┆            ┆           ┆           ┆        │
│ 62f5887d06 ┆         ┆ CET        ┆ CET        ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 00e319ee8d ┆ 1       ┆ 2025-08-16 ┆ 2025-08-16 ┆ … ┆ 6.0        ┆ 36        ┆ 2         ┆ 2.738  │
│ 96cc0dbdba ┆         ┆ 12:49:08   ┆ 12:54:35   ┆   ┆            ┆           ┆           ┆        │
│ 66f27707a3 ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 00347ff2dc ┆ 1       ┆ 2025-04-30 ┆ 2025-04-30 ┆ … ┆ 0.0        ┆ 7         ┆ 0         ┆ 65.05  │
│ 3587d0df15 ┆         ┆ 06:24:59   ┆ 06:49:06   ┆   ┆            ┆           ┆           ┆        │
│ 8fa14f9a3c ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 00a78669ba ┆ 1       ┆ 2025-02-14 ┆ 2025-02-14 ┆ … ┆ 0.0        ┆ 2         ┆ 2         ┆ 6.96   │
│ 2d88b092e4 ┆         ┆ 01:11:13   ┆ 01:21:40   ┆   ┆            ┆           ┆           ┆        │
│ 476a294ce1 ┆         ┆ CET        ┆ CET        ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 0005830e04 ┆ 1       ┆ 2025-08-30 ┆ 2025-08-30 ┆ … ┆ 0.0        ┆ 20        ┆ 1         ┆ 11.185 │
│ f56ea36c12 ┆         ┆ 02:11:03   ┆ 05:48:39   ┆   ┆            ┆           ┆           ┆        │
│ 449f4f36b0 ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ …          ┆ …       ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …      │
│ 002c3d7cb9 ┆ 1       ┆ 2024-12-06 ┆ 2024-12-06 ┆ … ┆ 0.0        ┆ 2         ┆ 3         ┆ 0.119  │
│ 48209a7b8f ┆         ┆ 09:21:38   ┆ 09:28:52   ┆   ┆            ┆           ┆           ┆        │
│ 64b0c7378c ┆         ┆ CET        ┆ CET        ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 00e45daa0c ┆ 1       ┆ 2025-10-30 ┆ 2025-10-30 ┆ … ┆ 3.0        ┆ 3         ┆ 3         ┆ 3.231  │
│ 2a0fa71238 ┆         ┆ 20:57:48   ┆ 21:08:19   ┆   ┆            ┆           ┆           ┆        │
│ 22319c782a ┆         ┆ CET        ┆ CET        ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 00f0ab95ff ┆ 1       ┆ 2025-12-04 ┆ 2025-12-04 ┆ … ┆ 0.0        ┆ 2         ┆ 5         ┆ 2.578  │
│ ccce64359b ┆         ┆ 15:16:58   ┆ 15:27:31   ┆   ┆            ┆           ┆           ┆        │
│ 6740733d97 ┆         ┆ CET        ┆ CET        ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 000c015683 ┆ 1       ┆ 2025-05-30 ┆ 2025-05-30 ┆ … ┆ 0.0        ┆ 2         ┆ 0         ┆ 0.0    │
│ 7060ae0bfa ┆         ┆ 14:37:40   ┆ 14:45:21   ┆   ┆            ┆           ┆           ┆        │
│ c5348d158f ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
│ 0055d45880 ┆ 1       ┆ 2025-08-21 ┆ 2025-08-21 ┆ … ┆ 14.0       ┆ 4         ┆ 1         ┆ 5.884  │
│ 7ab5c2e692 ┆         ┆ 07:21:25   ┆ 07:31:00   ┆   ┆            ┆           ┆           ┆        │
│ c82a724bcd ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴────────┘

In [ ]:
temp.group_by(pl.col.device_id).with_columns(pl.col.longitude_mean)

In [ ]:
def calculate_radius_of_gyration(data, weighted: bool = False):
    rcm_lon = data["lon"].mean()
    rcm_lat = data["lat"].mean()
    freq = data.groupby(["x", "y"])["t"].count().to_dict()
    ds = []
    w = 0
    for row in data.itertuples():
        w += freq[(row.x, row.y)]
        d = haversine((rcm_lat, rcm_lon), (row.lat, row.lon), unit=Unit.METERS) ** 2
        if weighted:
            d *= freq[(row.x, row.y)]
        ds.append(d)

    sum_ = np.sum(ds)
    N = len(data)
    if weighted:
        N = w
    return np.round(np.sqrt(sum_ / N) / 1000, 3)