In [1]:
import polars as pl
import yaml

with open("../config.budapest.yaml") as fp:
    config = yaml.safe_load(fp)

In [2]:
DIR = f"{config['dirs']['output']}/{config['city']}_ids_not_replaced"

In [3]:
for i in range(1):
    temp = pl.read_parquet(f"{DIR}/stops/v2/{i:02x}.parquet")

In [5]:
temp

shape: (548_130, 11)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ device_id  ┆ stop_id ┆ interval_ ┆ interval_ ┆ … ┆ latitude_ ┆ longitude ┆ number_of ┆ place_lab │
│ ---        ┆ ---     ┆ start     ┆ stop      ┆   ┆ std       ┆ _std      ┆ _pings    ┆ el        │
│ str        ┆ i32     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ datetime[ ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ u32       ┆ i64       │
│            ┆         ┆ μs, Europ ┆ μs, Europ ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ e/Budapes ┆ e/Budapes ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ t]        ┆ t]        ┆   ┆           ┆           ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 0.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 07:24:06  ┆ 07:35:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 2       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 4.0       ┆ 1.0       ┆ 2         ┆ 11        │
│ 6276495c5a ┆         ┆ 2         ┆ 2         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:23:47  ┆ 10:33:00  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 3       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 3         ┆ 3         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 10:50:40  ┆ 10:58:29  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 4       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 2         ┆ 12        │
│ 6276495c5a ┆         ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 12:41:20  ┆ 12:49:26  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ 0000051fc2 ┆ 5       ┆ 2024-10-0 ┆ 2024-10-0 ┆ … ┆ 0.0       ┆ 0.0       ┆ 4         ┆ 12        │
│ 6276495c5a ┆         ┆ 5         ┆ 5         ┆   ┆           ┆           ┆           ┆           │
│ 9ab1753a70 ┆         ┆ 11:06:43  ┆ 11:22:57  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CEST      ┆ CEST      ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00ffd69f07 ┆ 381     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 14.0      ┆ 12.0      ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 18:27:21  ┆ 18:37:33  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 382     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 11.0      ┆ 6.0       ┆ 3         ┆ 4         │
│ 86f191b711 ┆         ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 21:11:36  ┆ 21:26:20  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 383     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 9.0       ┆ 2.0       ┆ 4         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 04:47:22  ┆ 05:13:19  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 384     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 5.0       ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 08:04:50  ┆ 08:27:17  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
│ 00ffd69f07 ┆ 385     ┆ 2024-11-1 ┆ 2024-11-1 ┆ … ┆ 6.0       ┆ 13.0      ┆ 6         ┆ 4         │
│ 86f191b711 ┆         ┆ 8         ┆ 8         ┆   ┆           ┆           ┆           ┆           │
│ f219fd6605 ┆         ┆ 09:08:14  ┆ 09:43:51  ┆   ┆           ┆           ┆           ┆           │
│ …          ┆         ┆ CET       ┆ CET       ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
import polars_distance as pld
# https://ion-elgreco.github.io/polars-distance/api/dist/#polars_distance.DistancePairWise.haversine

In [ ]:
test = temp.filter(pl.col.device_id.str.starts_with("0000051fc26276495c5a9ab1753a70"))[
    :3
].clone()

In [ ]:
def rg(data: pl.DataFrame) -> pl.DataFrame:
    d = data.with_columns(
        pl.struct("longitude_mean", "latitude_mean")
        .alias("stop")
        .struct.rename_fields(["longitude", "latitude"]),
        pl.struct(pl.col.longitude_mean.mean(), pl.col.latitude_mean.mean())
        .alias("centroid")
        .struct.rename_fields(["longitude", "latitude"]),
    ).with_columns(
        pld.col("centroid").dist.haversine("stop", "km").alias("haversine"),
        pl.col.interval_lenght.dt.total_seconds().sum().alias("N"),
    )
    res = (
        ((d["haversine"] ** 2 * d["interval_lenght"].dt.total_seconds()).sum() / d["N"])
        .sqrt()
        .round(3)[0]
    )
    return data.head(1).with_columns(pl.lit(res).alias("result"))

In [76]:
temp.head(1).with_columns(pl.lit(0).alias("result"))

shape: (1, 12)
┌────────────┬─────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬────────┐
│ device_id  ┆ stop_id ┆ interval_s ┆ interval_s ┆ … ┆ longitude_ ┆ number_of ┆ place_lab ┆ result │
│ ---        ┆ ---     ┆ tart       ┆ top        ┆   ┆ std        ┆ _pings    ┆ el        ┆ ---    │
│ str        ┆ i32     ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ i32    │
│            ┆         ┆ datetime[μ ┆ datetime[μ ┆   ┆ f64        ┆ u32       ┆ i64       ┆        │
│            ┆         ┆ s, Europe/ ┆ s, Europe/ ┆   ┆            ┆           ┆           ┆        │
│            ┆         ┆ Budapest]  ┆ Budapest]  ┆   ┆            ┆           ┆           ┆        │
╞════════════╪═════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪════════╡
│ 0000051fc2 ┆ 1       ┆ 2024-10-02 ┆ 2024-10-02 ┆ … ┆ 0.0        ┆ 2         ┆ 11        ┆ 0      │
│ 6276495c5a ┆         ┆ 07:24:06   ┆ 07:35:29   ┆   ┆            ┆           ┆           ┆        │
│ 9ab1753a70 ┆         ┆ CEST       ┆ CEST       ┆   ┆            ┆           ┆           ┆        │
│ …          ┆         ┆            ┆            ┆   ┆            ┆           ┆           ┆        │
└────────────┴─────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴────────┘

In [ ]:
q = rg(test)
q

8.241283721822473

In [50]:
((q["haversine"] ** 2 * q["interval_lenght"].dt.total_seconds()).sum() / q["N"]).sqrt()

shape: (3,)
Series: 'N' [f64]
[
	8.241284
	8.241284
	8.241284
]

In [81]:
temp.group_by("device_id").map_groups(rg)

shape: (4_696, 16)
┌─────────────┬─────────┬─────────────┬─────────────┬───┬────────────┬───────────┬────────┬────────┐
│ device_id   ┆ stop_id ┆ interval_st ┆ interval_st ┆ … ┆ centroid   ┆ haversine ┆ N      ┆ result │
│ ---         ┆ ---     ┆ art         ┆ op          ┆   ┆ ---        ┆ ---       ┆ ---    ┆ ---    │
│ str         ┆ i32     ┆ ---         ┆ ---         ┆   ┆ struct[2]  ┆ f64       ┆ i64    ┆ f64    │
│             ┆         ┆ datetime[μs ┆ datetime[μs ┆   ┆            ┆           ┆        ┆        │
│             ┆         ┆ , Europe/Bu ┆ , Europe/Bu ┆   ┆            ┆           ┆        ┆        │
│             ┆         ┆ dapest]     ┆ dapest]     ┆   ┆            ┆           ┆        ┆        │
╞═════════════╪═════════╪═════════════╪═════════════╪═══╪════════════╪═══════════╪════════╪════════╡
│ 00f70fce9f3 ┆ 1       ┆ 2023-10-27  ┆ 2023-10-27  ┆ … ┆ {19.190824 ┆ 2.647667  ┆ 146016 ┆ 14.244 │
│ bb2942e9238 ┆         ┆ 02:15:10    ┆ 02:22:04    ┆   ┆ ,47.527842 ┆           ┆        ┆        │
│ dfd9960b…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 0093107f977 ┆ 1       ┆ 2024-10-05  ┆ 2024-10-05  ┆ … ┆ {18.830269 ┆ 0.397394  ┆ 2130   ┆ 0.514  │
│ 19ed33f6e48 ┆         ┆ 02:35:08    ┆ 02:53:35    ┆   ┆ ,47.438448 ┆           ┆        ┆        │
│ e030b01d…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 009694d5bba ┆ 1       ┆ 2025-12-23  ┆ 2025-12-23  ┆ … ┆ {19.9749,4 ┆ 0.0       ┆ 440    ┆ 0.0    │
│ cb1ecb734bb ┆         ┆ 16:09:02    ┆ 16:16:22    ┆   ┆ 8.034006}  ┆           ┆        ┆        │
│ 62a9c854…   ┆         ┆ CET         ┆ CET         ┆   ┆            ┆           ┆        ┆        │
│ 004c98e5a49 ┆ 1       ┆ 2025-08-28  ┆ 2025-08-28  ┆ … ┆ {19.092882 ┆ 2.48538   ┆ 76444  ┆ 2.132  │
│ ac8a2d7e251 ┆         ┆ 15:19:15    ┆ 15:30:32    ┆   ┆ ,47.507695 ┆           ┆        ┆        │
│ 5e51373c…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 00b8434096b ┆ 1       ┆ 2023-12-13  ┆ 2023-12-13  ┆ … ┆ {19.128227 ┆ 12.157867 ┆ 629884 ┆ 7.974  │
│ fdc9ec58857 ┆         ┆ 09:42:55    ┆ 09:52:14    ┆   ┆ ,47.550818 ┆           ┆        ┆        │
│ a147bb7b…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
│ …           ┆ …       ┆ …           ┆ …           ┆ … ┆ …          ┆ …         ┆ …      ┆ …      │
│ 00599b7d2ee ┆ 1       ┆ 2025-06-22  ┆ 2025-06-22  ┆ … ┆ {19.111834 ┆ 7.793884  ┆ 2195   ┆ 5.67   │
│ 8d06336ca49 ┆         ┆ 20:20:57    ┆ 20:34:34    ┆   ┆ ,47.49461} ┆           ┆        ┆        │
│ c98ca5e4…   ┆         ┆ CEST        ┆ CEST        ┆   ┆            ┆           ┆        ┆        │
│ 00e88bd3e0f ┆ 1       ┆ 2023-11-05  ┆ 2023-11-05  ┆ … ┆ {18.844284 ┆ 21.345006 ┆ 3951   ┆ 18.971 │
│ cd94d5e4aa5 ┆         ┆ 09:44:29    ┆ 09:50:38    ┆   ┆ ,47.367169 ┆           ┆        ┆        │
│ aeb046b3…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
│ 001db4a1248 ┆ 1       ┆ 2025-07-15  ┆ 2025-07-15  ┆ … ┆ {19.121671 ┆ 8.620419  ┆ 871653 ┆ 4.303  │
│ ca9db6d1cf5 ┆         ┆ 09:18:09    ┆ 10:09:34    ┆   ┆ ,47.510319 ┆           ┆        ┆        │
│ 38f0fca2…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 002564c6cc0 ┆ 1       ┆ 2025-05-04  ┆ 2025-05-04  ┆ … ┆ {19.176849 ┆ 12.24473  ┆ 715191 ┆ 13.304 │
│ 82f3b0c0c48 ┆         ┆ 10:32:19    ┆ 10:42:42    ┆   ┆ ,47.432964 ┆           ┆        ┆        │
│ 5dd70bfa…   ┆         ┆ CEST        ┆ CEST        ┆   ┆ }          ┆           ┆        ┆        │
│ 004416a7490 ┆ 1       ┆ 2023-12-13  ┆ 2023-12-13  ┆ … ┆ {19.101195 ┆ 2.428283  ┆ 48798  ┆ 5.447  │
│ 583d7ec56cd ┆         ┆ 02:12:26    ┆ 04:49:40    ┆   ┆ ,47.436017 ┆           ┆        ┆        │
│ 1ee93813…   ┆         ┆ CET         ┆ CET         ┆   ┆ }          ┆           ┆        ┆        │
└─────────────┴─────────┴─────────────┴─────────────┴───┴────────────┴───────────┴────────┴────────┘