In [ ]:
from datetime import datetime
from pathlib import Path

import polars as pl
import polars_distance as pld

In [2]:
DIR = "/mnt/common-ssd/group-dirs/tkom-2026-project/pickwell/budapest/partitioned/"

In [11]:
test = pl.DataFrame(
    {
        "device_id": [1, 1, 1, 1, 2, 2, 2],
        "timestamp": [
            datetime(2026, 10, 19, 10, 42, 38),
            datetime(2026, 10, 19, 10, 42, 59),
            datetime(2026, 10, 19, 10, 44, 11),
            datetime(2026, 10, 19, 10, 43, 7),
            datetime(2026, 10, 18, 17, 15, 43),
            datetime(2026, 10, 18, 17, 15, 49),
            datetime(2026, 10, 18, 17, 18, 2),
        ],
        "longitude": [
            19.033973,
            19.0334969,
            19.0321977,
            19.0326872,
            19.1095298,
            19.1099686,
            19.1165223,
        ],
        "latitude": [
            47.501812,
            47.501803,
            47.501977,
            47.501878,
            47.472143,
            47.471786,
            47.470600,
        ],
    }
)

In [9]:
def calculate_distance(data: pl.DataFrame) -> pl.DataFrame:
    return (
        data.with_columns(
            pl.col("latitude")
            .shift()
            .over("device_id", order_by="timestamp")
            .alias("prev_latitude"),
            pl.col("longitude")
            .shift()
            .over("device_id", order_by="timestamp")
            .alias("prev_longitude"),
        )
        .with_columns(
            pl.struct(
                pl.col("latitude").alias("latitude"),
                pl.col("longitude").alias("longitude"),
            ).alias("current_point"),
            pl.struct(
                pl.col("prev_latitude").alias("latitude"),
                pl.col("prev_longitude").alias("longitude"),
            ).alias("previous_point"),
        )
        .with_columns(
            pld.col("current_point")
            .dist.haversine("previous_point", unit="km")
            .alias("distance_km")
        )
        .with_columns(
            pl.col("timestamp")
            .diff()
            .over("device_id", order_by="timestamp")
            .alias("time_diff")
        )
    )

In [14]:
calculate_distance(test.sort(["device_id", "timestamp"]))

shape: (7, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ device_id ┆ timestamp ┆ longitude ┆ latitude  ┆ … ┆ current_p ┆ previous_ ┆ distance_ ┆ time_dif │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ oint      ┆ point     ┆ km        ┆ f        │
│ i64       ┆ datetime[ ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ μs]       ┆           ┆           ┆   ┆ struct[2] ┆ struct[2] ┆ f64       ┆ duration │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ [μs]     │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2026-10-1 ┆ 19.033973 ┆ 47.501812 ┆ … ┆ {47.50181 ┆ {null,nul ┆ null      ┆ null     │
│           ┆ 9         ┆           ┆           ┆   ┆ 2,19.0339 ┆ l}        ┆           ┆          │
│           ┆ 10:42:38  ┆           ┆           ┆   ┆ 73}       ┆           ┆           ┆          │
│ 1         ┆ 2026-10-1 ┆ 19.033497 ┆ 47.501803 ┆ … ┆ {47.50180 ┆ {47.50181 ┆ 0.035778  ┆ 21s      │
│           ┆ 9         ┆           ┆           ┆   ┆ 3,19.0334 ┆ 2,19.0339 ┆           ┆          │
│           ┆ 10:42:59  ┆           ┆           ┆   ┆ 97}       ┆ 73}       ┆           ┆          │
│ 1         ┆ 2026-10-1 ┆ 19.032687 ┆ 47.501878 ┆ … ┆ {47.50187 ┆ {47.50180 ┆ 0.061393  ┆ 8s       │
│           ┆ 9         ┆           ┆           ┆   ┆ 8,19.0326 ┆ 3,19.0334 ┆           ┆          │
│           ┆ 10:43:07  ┆           ┆           ┆   ┆ 87}       ┆ 97}       ┆           ┆          │
│ 1         ┆ 2026-10-1 ┆ 19.032198 ┆ 47.501977 ┆ … ┆ {47.50197 ┆ {47.50187 ┆ 0.038383  ┆ 1m 4s    │
│           ┆ 9         ┆           ┆           ┆   ┆ 7,19.0321 ┆ 8,19.0326 ┆           ┆          │
│           ┆ 10:44:11  ┆           ┆           ┆   ┆ 98}       ┆ 87}       ┆           ┆          │
│ 2         ┆ 2026-10-1 ┆ 19.10953  ┆ 47.472143 ┆ … ┆ {47.47214 ┆ {null,nul ┆ null      ┆ null     │
│           ┆ 8         ┆           ┆           ┆   ┆ 3,19.1095 ┆ l}        ┆           ┆          │
│           ┆ 17:15:43  ┆           ┆           ┆   ┆ 3}        ┆           ┆           ┆          │
│ 2         ┆ 2026-10-1 ┆ 19.109969 ┆ 47.471786 ┆ … ┆ {47.47178 ┆ {47.47214 ┆ 0.05161   ┆ 6s       │
│           ┆ 8         ┆           ┆           ┆   ┆ 6,19.1099 ┆ 3,19.1095 ┆           ┆          │
│           ┆ 17:15:49  ┆           ┆           ┆   ┆ 69}       ┆ 3}        ┆           ┆          │
│ 2         ┆ 2026-10-1 ┆ 19.116522 ┆ 47.4706   ┆ … ┆ {47.4706, ┆ {47.47178 ┆ 0.509946  ┆ 2m 13s   │
│           ┆ 8         ┆           ┆           ┆   ┆ 19.116522 ┆ 6,19.1099 ┆           ┆          │
│           ┆ 17:18:02  ┆           ┆           ┆   ┆ }         ┆ 69}       ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
Path(f"{DIR}/with_distance/").mkdir(exist_ok=True, parents=True)
for i in range(2):
    df = pl.read_parquet(f"{DIR}/{i:02x}/pings.parquet")
    df = calculate_distance(df)
    df.drop(
        ["prev_latitude", "prev_longitude", "current_point", "previous_point"]
    ).write_parquet(f"{DIR}/with_distance/{i:02x}.parquet")

In [ ]:
df.drop(["prev_latitude", "prev_longitude", "current_point", "previous_point"])

shape: (15_400_488, 8)
┌────────────┬───────────┬────────────┬───────────┬───────────┬────────────┬───────────┬───────────┐
│ timestamp  ┆ device_id ┆ device_aid ┆ latitude  ┆ longitude ┆ id_with_ty ┆ distance_ ┆ time_diff │
│ ---        ┆ ---       ┆ _type      ┆ ---       ┆ ---       ┆ pe         ┆ km        ┆ ---       │
│ datetime[μ ┆ i64       ┆ ---        ┆ f64       ┆ f64       ┆ ---        ┆ ---       ┆ duration[ │
│ s, Europe/ ┆           ┆ str        ┆           ┆           ┆ str        ┆ f64       ┆ μs]       │
│ Budapest]  ┆           ┆            ┆           ┆           ┆            ┆           ┆           │
╞════════════╪═══════════╪════════════╪═══════════╪═══════════╪════════════╪═══════════╪═══════════╡
│ 2025-08-30 ┆ 6587      ┆ AAID       ┆ 47.528802 ┆ 19.049234 ┆ 0100028f0f ┆ null      ┆ null      │
│ 06:25:28   ┆           ┆            ┆           ┆           ┆ 10a6257e84 ┆           ┆           │
│ CEST       ┆           ┆            ┆           ┆           ┆ c46662f199 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2024-01-17 ┆ 6588      ┆ AAID       ┆ 47.556306 ┆ 19.102451 ┆ 01000917fe ┆ null      ┆ null      │
│ 00:58:13   ┆           ┆            ┆           ┆           ┆ 3ff163cfe3 ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ 8d480258c4 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2024-01-17 ┆ 6588      ┆ AAID       ┆ 47.556303 ┆ 19.102439 ┆ 01000917fe ┆ 0.000991  ┆ 18m 51s   │
│ 01:17:04   ┆           ┆            ┆           ┆           ┆ 3ff163cfe3 ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ 8d480258c4 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2024-01-17 ┆ 6588      ┆ AAID       ┆ 47.556306 ┆ 19.102451 ┆ 01000917fe ┆ 0.000991  ┆ 1m 9s     │
│ 01:18:13   ┆           ┆            ┆           ┆           ┆ 3ff163cfe3 ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ 8d480258c4 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2024-01-17 ┆ 6588      ┆ AAID       ┆ 47.556306 ┆ 19.102451 ┆ 01000917fe ┆ 0.0       ┆ 19m 22s   │
│ 01:37:35   ┆           ┆            ┆           ┆           ┆ 3ff163cfe3 ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ 8d480258c4 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ …          ┆ …         ┆ …          ┆ …         ┆ …         ┆ …          ┆ …         ┆ …         │
│ 2025-12-21 ┆ 13220     ┆ AAID       ┆ 47.663946 ┆ 19.609275 ┆ 01fff1da22 ┆ 10.652959 ┆ 5m 12s    │
│ 15:19:34   ┆           ┆            ┆           ┆           ┆ 9019692a1e ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ d0ad2cddd1 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2025-12-21 ┆ 13220     ┆ AAID       ┆ 47.684819 ┆ 19.668607 ┆ 01fff1da22 ┆ 5.012059  ┆ 5m 30s    │
│ 15:25:04   ┆           ┆            ┆           ┆           ┆ 9019692a1e ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ d0ad2cddd1 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2025-12-21 ┆ 13220     ┆ AAID       ┆ 47.706548 ┆ 20.110039 ┆ 01fff1da22 ┆ 33.1258   ┆ 15m       │
│ 15:40:04   ┆           ┆            ┆           ┆           ┆ 9019692a1e ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ d0ad2cddd1 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2025-12-21 ┆ 13220     ┆ AAID       ┆ 47.708221 ┆ 20.012656 ┆ 01fff1da22 ┆ 7.289074  ┆ 14m 54s   │
│ 15:54:58   ┆           ┆            ┆           ┆           ┆ 9019692a1e ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ d0ad2cddd1 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
│ 2025-12-21 ┆ 13220     ┆ AAID       ┆ 47.708209 ┆ 20.012729 ┆ 01fff1da22 ┆ 0.005622  ┆ 9m 49s    │
│ 16:04:47   ┆           ┆            ┆           ┆           ┆ 9019692a1e ┆           ┆           │
│ CET        ┆           ┆            ┆           ┆           ┆ d0ad2cddd1 ┆           ┆           │
│            ┆           ┆            ┆           ┆           ┆ …          ┆           ┆           │
└────────────┴───────────┴────────────┴───────────┴───────────┴────────────┴───────────┴───────────┘